In [31]:
from cobra import Configuration
Configuration().solver = "glpk"

In [32]:
from cobra.io import load_json_model
model = load_json_model("../model/Saccharopolyspora_spinosa_boundaries.json")

In [33]:
model

In [21]:
model.metabolites

[<Metabolite C00001_c at 0x1d611108370>,
 <Metabolite C00002_c at 0x1d61111da90>,
 <Metabolite C00003_c at 0x1d61111d9f0>,
 <Metabolite C00004_c at 0x1d61111d310>,
 <Metabolite C00005_c at 0x1d61111dd10>,
 <Metabolite C00006_c at 0x1d61111de50>,
 <Metabolite C00007_c at 0x1d61111e350>,
 <Metabolite C00008_c at 0x1d61111d6d0>,
 <Metabolite C00009_c at 0x1d61111dc70>,
 <Metabolite C00010_c at 0x1d61111e030>,
 <Metabolite C00011_c at 0x1d61111e3f0>,
 <Metabolite C00012_c at 0x1d61111e170>,
 <Metabolite C00013_c at 0x1d61111e2b0>,
 <Metabolite C00014_c at 0x1d61111e210>,
 <Metabolite C00015_c at 0x1d61111ddb0>,
 <Metabolite C00016_c at 0x1d61111e0d0>,
 <Metabolite C00017_c at 0x1d61111def0>,
 <Metabolite C00018_c at 0x1d61111e850>,
 <Metabolite C00019_c at 0x1d61111e7b0>,
 <Metabolite C00020_c at 0x1d61111e710>,
 <Metabolite C00021_c at 0x1d61111e670>,
 <Metabolite C00022_c at 0x1d61111e490>,
 <Metabolite C00024_c at 0x1d61111ead0>,
 <Metabolite C00025_c at 0x1d61111e530>,
 <Metabolite C00026_c at 0x1d61111ecb0>,
 <Metabolite C00027_c at 0x1d61111ec10>,
 <Metabolite C00028_c at 0x1d61111eb70>,
 <Metabolite C00029_c at 0x1d61111f890>,
 <Metabolite C00030_c at 0x1d61111e8f0>,
 <Metabolite C00031_c at 0x1d61111e5d0>,
 <Metabolite C00032_c at 0x1d61111e990>,
 <Metabolite C00033_c at 0x1d61111ea30>,
 <Metabolite C00035_c at 0x1d61111edf0>,
 <Metabolite C00036_c at 0x1d61111f070>,
 <Metabolite C00037_c at 0x1d61111f1b0>,
 <Metabolite C00039_c at 0x1d61111ef30>,
 <Metabolite C00041_c at 0x1d61111ed50>,
 <Metabolite C00042_c at 0x1d61111f250>,
 <Metabolite C00043_c at 0x1d61111f390>,
 <Metabolite C00044_c at 0x1d61111f4d0>,
 <Metabolite C00046_c at 0x1d61111f110>,
 <Metabolite C00047_c at 0x1d61111efd0>,
 <Metabolite C00048_c at 0x1d61111f570>,
 <Metabolite C00049_c at 0x1d61111f6b0>,
 <Metabolite C00051_c at 0x1d61111fa70>,
 <Metabolite C00052_c at 0x1d61111f7f0>,
 <Metabolite C00053_c at 0x1d61111f430>,
 <Metabolite C00054_c at 0x1d61111f2f0>,
 <Metabolite C00055_c at 0x1d61111f930>,
 <Metabolite C00058_c at 0x1d61111fcf0>,
 <Metabolite C00059_c at 0x1d61111fc50>,
 <Metabolite C00061_c at 0x1d61111fbb0>,
 <Metabolite C00062_c at 0x1d61111f750>,
 <Metabolite C00063_c at 0x1d61111f610>,
 <Metabolite C00064_c at 0x1d61111fd90>,
 <Metabolite C00065_c at 0x1d61111fe30>,
 <Metabolite C00067_c at 0x1d61111fb10>,
 <Metabolite C00072_c at 0x1d61111f9d0>,
 <Metabolite C00073_c at 0x1d61111ff70>,
 <Metabolite C00074_c at 0x1d61111fed0>,
 <Metabolite C00075_c at 0x1d61112c5f0>,
 <Metabolite C00077_c at 0x1d61112c0f0>,
 <Metabolite C00078_c at 0x1d61112c050>,
 <Metabolite C00079_c at 0x1d61112c230>,
 <Metabolite C00080_c at 0x1d61112c190>,
 <Metabolite C00081_c at 0x1d61112c2d0>,
 <Metabolite C00082_c at 0x1d61112c410>,
 <Metabolite C00083_c at 0x1d61112c730>,
 <Metabolite C00084_c at 0x1d61112c910>,
 <Metabolite C00085_c at 0x1d61112c870>,
 <Metabolite C00086_c at 0x1d61112d130>,
 <Metabolite C00087_c at 0x1d61112c4b0>,
 <Metabolite C00088_c at 0x1d61112c9b0>,
 <Metabolite C00089_c at 0x1d61112cd70>,
 <Metabolite C00090_c at 0x1d61112ccd0>,
 <Metabolite C00091_c at 0x1d61112cc30>,
 <Metabolite C00092_c at 0x1d61112cb90>,
 <Metabolite C00093_c at 0x1d61112ca50>,
 <Metabolite C00094_c at 0x1d61112c690>,
 <Metabolite C00095_c at 0x1d61112c7d0>,
 <Metabolite C00096_c at 0x1d61112cf50>,
 <Metabolite C00097_c at 0x1d61112d310>,
 <Metabolite C00099_c at 0x1d61112d090>,
 <Metabolite C00100_c at 0x1d61112ceb0>,
 <Metabolite C00101_c at 0x1d61112caf0>,
 <Metabolite C00103_c at 0x1d61112d1d0>,
 <Metabolite C00104_c at 0x1d61112d590>,
 <Metabolite C00105_c at 0x1d61112d4f0>,
 <Metabolite C00106_c at 0x1d61112d450>,
 <Metabolite C00108_c at 0x1d61112cff0>,
 <Metabolite C00109_c at 0x1d61112ce10>,
 <Metabolite C00111_c at 0x1d61112d270>,
 <Metabolite C00112_c at 0x1d61112d6d0>,
 <Metabolite C00113_c at 0x1d61112d8b0>,
 <Metabolite C00114_c at 0x1d61112d810>,
 <Metabolite C00116_c at 0x1d61112d3b0>,
 <Metabolite C00117_c at 0x1d61112fed0>,
 <Metabolite C00118_c at 0x1d61112d950>,
 <Metabolite C00119_c at 0x1d61112dc70>,
 <Metabolite C00120_c at 0x1d61112dbd0>,
 <Metabolite C00121_c at 0x1d61112db30>,
 <Metabolite C00122_c at 0x1d61112d630>,
 <Metabolite C00123_c at 0x1d61112d9f0>,
 <Metabolite C00124_c at 0x1d61112dd10>,
 <Metabolite C00125_c at 0x1d61112ddb0>,
 <Metabolite C00126_c at 0x1d61112da90>,
 <Metabolite C00127_c at 0x1d61112fbb0>,
 <Metabolite C00129_c at 0x1d61112fa70>,
 <Metabolite C00130_c at 0x1d61112fd90>,
 <Metabolite C00131_c at 0x1d61112fcf0>,
 <Metabolite C00132_c at 0x1d61112ff70>,
 <Metabolite C00133_c at 0x1d61112fe30>,
 <Metabolite C00134_c at 0x1d61112f9d0>,
 <Metabolite C00135_c at 0x1d61112f930>,
 <Metabolite C00136_c at 0x1d61112fb10>,
 <Metabolite C00137_c at 0x1d61112f390>,
 <Metabolite C00140_c at 0x1d61112f7f0>,
 <Metabolite C00141_c at 0x1d61112f610>,
 <Metabolite C00143_c at 0x1d61112f890>,
 <Metabolite C00144_c at 0x1d61112f6b0>,
 <Metabolite C00146_c at 0x1d61112f4d0>,
 <Metabolite C00147_c at 0x1d61112f750>,
 <Metabolite C00148_c at 0x1d61112f2f0>,
 <Metabolite C00149_c at 0x1d61112f1b0>,
 <Metabolite C00152_c at 0x1d61112f070>,
 <Metabolite C00153_c at 0x1d61112f570>,
 <Metabolite C00154_c at 0x1d61112f430>,
 <Metabolite C00155_c at 0x1d61112efd0>,
 <Metabolite C00156_c at 0x1d61112edf0>,
 <Metabolite C00158_c at 0x1d61112ef30>,
 <Metabolite C00159_c at 0x1d61112f250>,
 <Metabolite C00160_c at 0x1d61112f110>,
 <Metabolite C00163_c at 0x1d61112e990>,
 <Metabolite C00164_c at 0x1d61112eb70>,
 <Metabolite C00166_c at 0x1d61112ecb0>,
 <Metabolite C00167_c at 0x1d61112ee90>,
 <Metabolite C00168_c at 0x1d61112ed50>,
 <Metabolite C00169_c at 0x1d61112e7b0>,
 <Metabolite C00170_c at 0x1d61112e8f0>,
 <Metabolite C00175_c at 0x1d61112ec10>,
 <Metabolite C00177_c at 0x1d61112ead0>,
 <Metabolite C00178_c at 0x1d61112e490>,
 <Metabolite C00179_c at 0x1d61112e5d0>,
 <Metabolite C00180_c at 0x1d61112e2b0>,
 <Metabolite C00183_c at 0x1d61112ea30>,
 <Metabolite C00184_c at 0x1d61112e850>,
 <Metabolite C00185_c at 0x1d61112e710>,
 <Metabolite C00186_c at 0x1d61112e170>,
 <Metabolite C00187_c at 0x1d61112df90>,
 <Metabolite C00188_c at 0x1d61112e670>,
 <Metabolite C00189_c at 0x1d61112e530>,
 <Metabolite C00191_c at 0x1d61112e3f0>,
 <Metabolite C00193_c at 0x1d61112e0d0>,
 <Metabolite C00194_c at 0x1d61112e350>,
 <Metabolite C00196_c at 0x1d61112e210>,
 <Metabolite C00197_c at 0x1d61112def0>,
 <Metabolite C00198_c at 0x1d61112d770>,
 <Metabolite C00199_c at 0x1d61115cb90>,
 <Metabolite C00203_c at 0x1d61115caf0>,
 <Metabolite C00204_c at 0x1d61115c870>,
 <Metabolite C00206_c at 0x1d61115fb10>,
 <Metabolite C00207_c at 0x1d61115fed0>,
 <Metabolite C00208_c at 0x1d61115fbb0>,
 <Metabolite C00209_c at 0x1d61115ff70>,
 <Metabolite C00212_c at 0x1d61115fcf0>,
 <Metabolite C00213_c at 0x1d61115fe30>,
 <Metabolite C00214_c at 0x1d61115f390>,
 <Metabolite C00217_c at 0x1d61115f890>,
 <Metabolite C00218_c at 0x1d61115f4d0>,
 <Metabolite C00219_c at 0x1d61115fc50>,
 <Metabolite C00222_c at 0x1d61115fd90>,
 <Metabolite C00223_c at 0x1d61115f7f0>,
 <Metabolite C00224_c at 0x1d61115fa70>,
 <Metabolite C00229_c at 0x1d61115f250>,
 <Metabolite C00230_c at 0x1d61115f9d0>,
 <Metabolite C00231_c at 0x1d61115f930>,
 <Metabolite C00232_c at 0x1d61115f750>,
 <Metabolite C00233_c at 0x1d61115f430>,
 <Metabolite C00234_c at 0x1d61115f570>,
 <Metabolite C00235_c at 0x1d61115ecb0>,
 <Metabolite C00236_c at 0x1d61115f610>,
 <Metabolite C00237_c at 0x1d61115f070>,
 <Metabolite C00239_c at 0x1d61115eb70>,
 <Metabolite C00242_c at 0x1d61115f6b0>,
 <Metabolite C00243_c at 0x1d61115ee90>,
 <Metabolite C00244_c at 0x1d61115f1b0>,
 <Metabolite C00245_c at 0x1d61115f110>,
 <Metabolite C00248_c at 0x1d61115ef30>,
 <Metabolite C00249_c at 0x1d61115efd0>,
 <Metabolite C00251_c at 0x1d61115e710>,
 <Metabolite C00253_c at 0x1d61115ead0>,
 <Metabolite C00254_c at 0x1d61115ed50>,
 <Metabolite C00255_c at 0x1d61115edf0>,
 <Metabolite C00256_c at 0x1d61115ec10>,
 <Metabolite C00257_c at 0x1d61115e7b0>,
 <Metabolite C00258_c at 0x1d61115e990>,
 <Metabolite C00261_c at 0x1d61115e5d0>,
 <Metabolite C00262_c at 0x1d61115e8f0>,
 <Metabolite C00263_c at 0x1d61115e350>,
 <Metabolite C00266_c at 0x1d61115e030>,
 <Metabolite C00268_c at 0x1d61115e670>,
 <Metabolite C00269_c at 0x1d61115def0>,
 <Metabolite C00275_c at 0x1d61115e850>,
 <Metabolite C00279_c at 0x1d61115e530>,
 <Metabolite C00280_c at 0x1d61115dd10>,
 <Metabolite C00283_c at 0x1d61115e3f0>,
 <Metabolite C00286_c at 0x1d61115e490>,
 <Metabolite C00288_c at 0x1d61115e2b0>,
 <Metabolite C00292_c at 0x1d61115e170>,
 <Metabolite C00294_c at 0x1d61115d810>,
 <Metabolite C00295_c at 0x1d61115df90>,
 <Metabolite C00299_c at 0x1d61115de50>,
 <Metabolite C00300_c at 0x1d61115e210>,
 <Metabolite C00301_c at 0x1d61115dbd0>,
 <Metabolite C00305_c at 0x1d61115d8b0>,
 <Metabolite C00310_c at 0x1d61115d9f0>,
 <Metabolite C00311_c at 0x1d61115e0d0>,
 <Metabolite C00312_c at 0x1d61115dc70>,
 <Metabolite C00313_c at 0x1d61115db30>,
 <Metabolite C00315_c at 0x1d61115d3b0>,
 <Metabolite C00320_c at 0x1d61115c050>,
 <Metabolite C00322_c at 0x1d61115da90>,
 <Metabolite C00323_c at 0x1d61115d950>,
 <Metabolite C00327_c at 0x1d61115d4f0>,
 <Metabolite C00328_c at 0x1d61115d6d0>,
 <Metabolite C00330_c at 0x1d61115d630>,
 <Metabolite C00332_c at 0x1d61115d090>,
 <Metabolite C00333_c at 0x1d61115d450>,
 <Metabolite C00334_c at 0x1d61115d310>,
 <Metabolite C00337_c at 0x1d61115ccd0>,
 <Metabolite C00341_c at 0x1d61115cff0>,
 <Metabolite C00344_c at 0x1d61115d130>,
 <Metabolite C00345_c at 0x1d61115d1d0>,
 <Metabolite C00349_c at 0x1d61115d590>,
 <Metabolite C00350_c at 0x1d61115d270>,
 <Metabolite C00352_c at 0x1d61115cf50>,
 <Metabolite C00353_c at 0x1d61115c910>,
 <Metabolite C00354_c at 0x1d61115ca50>,
 <Metabolite C00355_c at 0x1d61115ceb0>,
 <Metabolite C00356_c at 0x1d61115cd70>,
 <Metabolite C00357_c at 0x1d61115cc30>,
 <Metabolite C00360_c at 0x1d61115c2d0>,
 <Metabolite C00361_c at 0x1d61115c730>,
 <Metabolite C00362_c at 0x1d61115c5f0>,
 <Metabolite C00363_c at 0x1d61115c410>,
 <Metabolite C00364_c at 0x1d61115c7d0>,
 <Metabolite C00365_c at 0x1d61115c690>,
 <Metabolite C00366_c at 0x1d61115c550>,
 <Metabolite C00376_c at 0x1d61115c4b0>,
 <Metabolite C00378_c at 0x1d61115ddb0>,
 <Metabolite C00380_c at 0x1d61115c370>,
 <Metabolite C00385_c at 0x1d61115c230>,
 <Metabolite C00387_c at 0x1d61115c190>,
 <Metabolite C00388_c at 0x1d61115c0f0>,
 <Metabolite C00392_c at 0x1d61115c9b0>,
 <Metabolite C00398_c at 0x1d61115ce10>,
 <Metabolite C00402_c at 0x1d61124b930>,
 <Metabolite C00406_c at 0x1d611249450>,
 <Metabolite C00407_c at 0x1d61124bed0>,
 <Metabolite C00409_c at 0x1d61124b4d0>,
 <Metabolite C00410_c at 0x1d61124bd90>,
 <Metabolite C00411_c at 0x1d61124bf70>,
 <Metabolite C00412_c at 0x1d61124be30>,
 <Metabolite C00414_c at 0x1d61124bc50>,
 <Metabolite C00415_c at 0x1d61124bcf0>,
 <Metabolite C00416_c at 0x1d61124bbb0>,
 <Metabolite C00420_c at 0x1d61124b610>,
 <Metabolite C00422_c at 0x1d61124b890>,
 <Metabolite C00423_c at 0x1d61124b390>,
 <Metabolite C00424_c at 0x1d61124b9d0>,
 <Metabolite C00429_c at 0x1d61124b2f0>,
 <Metabolite C00430_c at 0x1d61124b6b0>,
 <Metabolite C00433_c at 0x1d61124b570>,
 <Metabolite C00437_c at 0x1d61124b1b0>,
 <Metabolite C00438_c at 0x1d61124b430>,
 <Metabolite C00439_c at 0x1d61124b070>,
 <Metabolite C00440_c at 0x1d61124ae90>,
 <Metabolite C00441_c at 0x1d61124adf0>,
 <Metabolite C00445_c at 0x1d61124af30>,
 <Metabolite C00446_c at 0x1d61124b110>,
 <Metabolite C00448_c at 0x1d61124afd0>,
 <Metabolite C00449_c at 0x1d61124acb0>,
 <Metabolite C00455_c at 0x1d61124ab70>,
 <Metabolite C00458_c at 0x1d611249d10>,
 <Metabolite C00459_c at 0x1d61124aa30>,
 <Metabolite C00460_c at 0x1d61124a990>,
 <Metabolite C00463_c at 0x1d61124ba70>,
 <Metabolite C00468_c at 0x1d61124ac10>,
 <Metabolite C00469_c at 0x1d61124aad0>,
 <Metabolite C00472_c at 0x1d61124a850>,
 <Metabolite C00473_c at 0x1d61124a670>,
 <Metabolite C00475_c at 0x1d61124a8f0>,
 <Metabolite C00479_c at 0x1d61124a3f0>,
 <Metabolite C00483_c at 0x1d61124a7b0>,
 <Metabolite C00487_c at 0x1d61124a350>,
 <Metabolite C00488_c at 0x1d61124a530>,
 <Metabolite C00490_c at 0x1d61124a710>,
 <Metabolite C00491_c at 0x1d61124a490>,
 <Metabolite C00492_c at 0x1d611249c70>,
 <Metabolite C00493_c at 0x1d61124a5d0>,
 <Metabolite C00499_c at 0x1d61124a030>,
 <Metabolite C00503_c at 0x1d61124a2b0>,
 <Metabolite C00507_c at 0x1d611249ef0>,
 <Metabolite C00510_c at 0x1d61124a0d0>,
 <Metabolite C00511_c at 0x1d611249f90>,
 <Metabolite C00512_c at 0x1d611249950>,
 <Metabolite C00513_c at 0x1d611249810>,
 <Metabolite C00514_c at 0x1d611249630>,
 <Metabolite C00515_c at 0x1d611249b30>,
 <Metabolite C00522_c at 0x1d6112498b0>,
 <Metabolite C00526_c at 0x1d6112494f0>,
 <Metabolite C00527_c at 0x1d611248410>,
 <Metabolite C00530_c at 0x1d6112496d0>,
 <Metabolite C00531_c at 0x1d611249270>,
 <Metabolite C00533_c at 0x1d611249590>,
 <Metabolite C00534_c at 0x1d611248f50>,
 <Metabolite C00535_c at 0x1d611249130>,
 <Metabolite C00536_c at 0x1d611249310>,
 <Metabolite C00540_c at 0x1d6112493b0>,
 <Metabolite C00542_c at 0x1d6112491d0>,
 <Metabolite C00543_c at 0x1d611248730>,
 <Metabolite C00544_c at 0x1d611248b90>,
 <Metabolite C00546_c at 0x1d611248e10>,
 <Metabolite C00547_c at 0x1d611248eb0>,
 <Metabolite C00552_c at 0x1d611248d70>,
 <Metabolite C00555_c at 0x1d61124a210>,
 <Metabolite C00558_c at 0x1d611248a50>,
 <Metabolite C00559_c at 0x1d611248c30>,
 <Metabolite C00566_c at 0x1d611248af0>,
 <Metabolite C00568_c at 0x1d6112489b0>,
 <Metabolite C00575_c at 0x1d611248cd0>,
 <Metabolite C00576_c at 0x1d611248690>,
 <Metabolite C00577_c at 0x1d6112487d0>,
 <Metabolite C00579_c at 0x1d611248910>,
 <Metabolite C00581_c at 0x1d6112480f0>,
 <Metabolite C00582_c at 0x1d6112485f0>,
 <Metabolite C00587_c at 0x1d611248190>,
 <Metabolite C00599_c at 0x1d6112484b0>,
 <Metabolite C00601_c at 0x1d611248550>,
 <Metabolite C00603_c at 0x1d611248370>,
 <Metabolite C00619_c at 0x1d611248230>,
 <Metabolite C00620_c at 0x1d611249e50>,
 <Metabolite C00624_c at 0x1d611248050>,
 <Metabolite C00627_c at 0x1d611249770>,
 <Metabolite C00628_c at 0x1d611249090>,
 <Metabolite C00631_c at 0x1d61124ad50>,
 <Metabolite C00632_c at 0x1d611248ff0>,
 <Metabolite C00633_c at 0x1d611248870>,
 <Metabolite C00636_c at 0x1d611249a90>,
 <Metabolite C00637_c at 0x1d61124a170>,
 <Metabolite C00643_c at 0x1d61124bb10>,
 <Metabolite C00645_c at 0x1d61124b250>,
 <Metabolite C00647_c at 0x1d6112499f0>,
 <Metabolite C00650_c at 0x1d61124b750>,
 <Metabolite C00655_c at 0x1d6112482d0>,
 <Metabolite C00666_c at 0x1d61124b7f0>,
 <Metabolite C00669_c at 0x1d6112b39d0>,
 <Metabolite C00670_c at 0x1d6112b3610>,
 <Metabolite C00671_c at 0x1d6112b3ed0>,
 <Metabolite C00672_c at 0x1d6112b3d90>,
 <Metabolite C00673_c at 0x1d6112b3750>,
 <Metabolite C00679_c at 0x1d6112b2c10>,
 <Metabolite C00680_c at 0x1d6112b3930>,
 <Metabolite C00683_c at 0x1d6112b2ad0>,
 <Metabolite C00688_c at 0x1d6112b37f0>,
 <Metabolite C00689_c at 0x1d6112b3890>,
 <Metabolite C00691_c at 0x1d6112b36b0>,
 <Metabolite C00692_c at 0x1d6112b2a30>,
 <Metabolite C00698_c at 0x1d6112b2df0>,
 <Metabolite C00700_c at 0x1d6112b27b0>,
 <Metabolite C00703_c at 0x1d6112b2850>,
 <Metabolite C00704_c at 0x1d6112b28f0>,
 <Metabolite C00705_c at 0x1d6112b2cb0>,
 <Metabolite C00712_c at 0x1d6112b3430>,
 <Metabolite C00719_c at 0x1d6112b2e90>,
 <Metabolite C00725_c at 0x1d6112b2fd0>,
 <Metabolite C00735_c at 0x1d6112b2f30>,
 <Metabolite C00740_c at 0x1d6112b3250>,
 <Metabolite C00741_c at 0x1d6112b2490>,
 <Metabolite C00744_c at 0x1d6112b1b30>,
 <Metabolite C00748_c at 0x1d6112b2530>,
 <Metabolite C00750_c at 0x1d6112b25d0>,
 <Metabolite C00751_c at 0x1d6112b2670>,
 <Metabolite C00763_c at 0x1d6112b2210>,
 <Metabolite C00777_c at 0x1d6112b19f0>,
 <Metabolite C00780_c at 0x1d6112b1c70>,
 <Metabolite C00785_c at 0x1d6112b1ef0>,
 <Metabolite C00788_c at 0x1d6112b1e50>,
 <Metabolite C00791_c at 0x1d6112b1f90>,
 <Metabolite C00792_c at 0x1d6112b1db0>,
 <Metabolite C00794_c at 0x1d6112b2030>,
 <Metabolite C00797_c at 0x1d6112b2170>,
 <Metabolite C00798_c at 0x1d6112b0eb0>,
 <Metabolite C00800_c at 0x1d6112b1810>,
 <Metabolite C00804_c at 0x1d6112b16d0>,
 <Metabolite C00805_c at 0x1d6112b1a90>,
 <Metabolite C00810_c at 0x1d6112b1950>,
 <Metabolite C00818_c at 0x1d6112b14f0>,
 <Metabolite C00819_c at 0x1d6112b1630>,
 <Metabolite C00826_c at 0x1d6112b1bd0>,
 <Metabolite C00829_c at 0x1d6112b1770>,
 <Metabolite C00831_c at 0x1d6112b1270>,
 <Metabolite C00842_c at 0x1d6112b1130>,
 <Metabolite C00846_c at 0x1d6112b0690>,
 <Metabolite C00850_c at 0x1d6112b11d0>,
 <Metabolite C00853_c at 0x1d6112b0cd0>,
 <Metabolite C00855_c at 0x1d6112b0d70>,
 <Metabolite C00857_c at 0x1d6112b0910>,
 <Metabolite C00860_c at 0x1d6112b07d0>,
 <Metabolite C00861_c at 0x1d6112b0410>,
 <Metabolite C00864_c at 0x1d6112b02d0>,
 <Metabolite C00870_c at 0x1d6112b0550>,
 <Metabolite C00876_c at 0x1d6112b0230>,
 <Metabolite C00877_c at 0x1d6112b0e10>,
 <Metabolite C00879_c at 0x1d6112b0050>,
 <Metabolite C00880_c at 0x1d6112b0190>,
 <Metabolite C00881_c at 0x1d6112b2350>,
 <Metabolite C00882_c at 0x1d6112b00f0>,
 <Metabolite C00885_c at 0x1d6112b3110>,
 <Metabolite C00894_c at 0x1d6112b20d0>,
 <Metabolite C00898_c at 0x1d6112b0870>,
 <Metabolite C00900_c at 0x1d6112b2b70>,
 <Metabolite C00905_c at 0x1d6112b34d0>,
 <Metabolite C00906_c at 0x1d6112b18b0>,
 <Metabolite C00916_c at 0x1d6112b23f0>,
 <Metabolite C00918_c at 0x1d6112b2d50>,
 <Metabolite C00919_c at 0x1d6112b3070>,
 <Metabolite C00921_c at 0x1d6112b2990>,
 <Metabolite C00923_c at 0x1d6112b3c50>,
 <Metabolite C00924_c at 0x1d6112b3a70>,
 <Metabolite C00931_c at 0x1d6112b0a50>,
 <Metabolite C00942_c at 0x1d6112b05f0>,
 <Metabolite C00944_c at 0x1d6112b2710>,
 <Metabolite C00951_c at 0x1d6112b31b0>,
 <Metabolite C00954_c at 0x1d6112b3390>,
 <Metabolite C00956_c at 0x1d6112b1310>,
 <Metabolite C00957_c at 0x1d6112b1090>,
 <Metabolite C00966_c at 0x1d6112b3570>,
 <Metabolite C00969_c at 0x1d6112b0af0>,
 <Metabolite C00979_c at 0x1d6112b0f50>,
 <Metabolite C00988_c at 0x1d6112b32f0>,
 <Metabolite C00993_c at 0x1d6112b1d10>,
 <Metabolite C01005_c at 0x1d6112b3bb0>,
 <Metabolite C01010_c at 0x1d6112b0370>,
 <Metabolite C01013_c at 0x1d6112b0b90>,
 <Metabolite C01019_c at 0x1d6112b0ff0>,
 <Metabolite C01024_c at 0x1d6112b3cf0>,
 <Metabolite C01034_c at 0x1d6112b3f70>,
 <Metabolite C01035_c at 0x1d6112b1450>,
 <Metabolite C01036_c at 0x1d6112b22b0>,
 <Metabolite C01037_c at 0x1d6112b04b0>,
 <Metabolite C01040_c at 0x1d6112b3b10>,
 <Metabolite C01050_c at 0x1d6112b3e30>,
 <Metabolite C01051_c at 0x1d6112b0730>,
 <Metabolite C01061_c at 0x1d6112b0c30>,
 <Metabolite C01063_c at 0x1d6112b13b0>,
 <Metabolite C01077_c at 0x1d611174910>,
 <Metabolite C01079_c at 0x1d611174410>,
 <Metabolite C01080_c at 0x1d6111749b0>,
 <Metabolite C01081_c at 0x1d611174e10>,
 <Metabolite C01083_c at 0x1d611174eb0>,
 <Metabolite C01089_c at 0x1d611174550>,
 <Metabolite C01092_c at 0x1d611174050>,
 <Metabolite C01096_c at 0x1d6111745f0>,
 <Metabolite C01097_c at 0x1d6111744b0>,
 <Metabolite C01099_c at 0x1d611174190>,
 <Metabolite C01100_c at 0x1d611174690>,
 <Metabolite C01102_c at 0x1d6111740f0>,
 <Metabolite C01103_c at 0x1d611174230>,
 <Metabolite C01110_c at 0x1d610994af0>,
 <Metabolite C01115_c at 0x1d6109949b0>,
 <Metabolite C01118_c at 0x1d610995c70>,
 <Metabolite C01127_c at 0x1d610997bb0>,
 <Metabolite C01131_c at 0x1d610996ad0>,
 <Metabolite C01134_c at 0x1d610996cb0>,
 <Metabolite C01137_c at 0x1d610997890>,
 <Metabolite C01144_c at 0x1d610997390>,
 <Metabolite C01146_c at 0x1d610996c10>,
 <Metabolite C01147_c at 0x1d610994a50>,
 <Metabolite C01149_c at 0x1d610996670>,
 <Metabolite C01152_c at 0x1d610994ff0>,
 <Metabolite C01153_c at 0x1d611142e90>,
 <Metabolite C01157_c at 0x1d6111436b0>,
 <Metabolite C01159_c at 0x1d611140cd0>,
 <Metabolite C01163_c at 0x1d611140c30>,
 <Metabolite C01165_c at 0x1d611140230>,
 <Metabolite C01171_c at 0x1d611143d90>,

In [22]:
model.reactions

[<Reaction R00004 at 0x1d611c787e0>,
 <Reaction R00005 at 0x1d611c78890>,
 <Reaction R00006 at 0x1d611c78940>,
 <Reaction R00009 at 0x1d611c789f0>,
 <Reaction R00013 at 0x1d611c78aa0>,
 <Reaction R00022 at 0x1d611c78b50>,
 <Reaction R00025 at 0x1d611c78c00>,
 <Reaction R00028 at 0x1d611c78cb0>,
 <Reaction R00036 at 0x1d611c78d60>,
 <Reaction R00066 at 0x1d611c78e10>,
 <Reaction R00069 at 0x1d611c78ec0>,
 <Reaction R00084 at 0x1d611c78f70>,
 <Reaction R00089 at 0x1d611c79020>,
 <Reaction R00093 at 0x1d611c790d0>,
 <Reaction R00094 at 0x1d611c79180>,
 <Reaction R00103 at 0x1d611c79230>,
 <Reaction R00104 at 0x1d611c792e0>,
 <Reaction R00106 at 0x1d611c79390>,
 <Reaction R00111 at 0x1d611c79440>,
 <Reaction R00112 at 0x1d611c794f0>,
 <Reaction R00114 at 0x1d611c795a0>,
 <Reaction R00115 at 0x1d611c79650>,
 <Reaction R00118 at 0x1d611c79700>,
 <Reaction R00130 at 0x1d611c797b0>,
 <Reaction R00131 at 0x1d611c79860>,
 <Reaction R00132 at 0x1d611c79910>,
 <Reaction R00137 at 0x1d611c799c0>,
 <Reaction R00139 at 0x1d611c79a70>,
 <Reaction R00161 at 0x1d611c79b20>,
 <Reaction R00177 at 0x1d611c79bd0>,
 <Reaction R00178 at 0x1d611c79c80>,
 <Reaction R00189 at 0x1d611c79d30>,
 <Reaction R00192 at 0x1d611c79de0>,
 <Reaction R00217 at 0x1d611c79e90>,
 <Reaction R00220 at 0x1d611c79f40>,
 <Reaction R00253 at 0x1d611c79ff0>,
 <Reaction R00254 at 0x1d611c7a0a0>,
 <Reaction R00257 at 0x1d611c7a150>,
 <Reaction R00264 at 0x1d611c7a200>,
 <Reaction R00272 at 0x1d611c7a2b0>,
 <Reaction R00275 at 0x1d611c7a360>,
 <Reaction R00277 at 0x1d611c7a410>,
 <Reaction R00278 at 0x1d611c7a4c0>,
 <Reaction R00286 at 0x1d611c7a570>,
 <Reaction R00306 at 0x1d611c7a620>,
 <Reaction R00310 at 0x1d611c7a6d0>,
 <Reaction R00321 at 0x1d611c7a780>,
 <Reaction R00335 at 0x1d611c7a830>,
 <Reaction R00354 at 0x1d611c7a8e0>,
 <Reaction R00357 at 0x1d611c7a990>,
 <Reaction R00366 at 0x1d611c7aa40>,
 <Reaction R00371 at 0x1d611c7aaf0>,
 <Reaction R00372 at 0x1d611c7aba0>,
 <Reaction R00418 at 0x1d611c7ac50>,
 <Reaction R00424 at 0x1d611c7ad00>,
 <Reaction R00425 at 0x1d611c7adb0>,
 <Reaction R00428 at 0x1d611c7ae60>,
 <Reaction R00429 at 0x1d611c7af10>,
 <Reaction R00434 at 0x1d611c7afc0>,
 <Reaction R00457 at 0x1d611c7b070>,
 <Reaction R00470 at 0x1d611c7b120>,
 <Reaction R00471 at 0x1d611c7b1d0>,
 <Reaction R00475 at 0x1d611c7b280>,
 <Reaction R00481 at 0x1d611c7b330>,
 <Reaction R00489 at 0x1d611c7b3e0>,
 <Reaction R00490 at 0x1d611c7b490>,
 <Reaction R00491 at 0x1d611c7b540>,
 <Reaction R00494 at 0x1d611c7b5f0>,
 <Reaction R00505 at 0x1d611c7b6a0>,
 <Reaction R00513 at 0x1d61134fee0>,
 <Reaction R00516 at 0x1d61134f1d0>,
 <Reaction R00517 at 0x1d61134c310>,
 <Reaction R00519 at 0x1d61134c260>,
 <Reaction R00524 at 0x1d61134ef10>,
 <Reaction R00549 at 0x1d61134ed00>,
 <Reaction R00551 at 0x1d61134f3e0>,
 <Reaction R00552 at 0x1d61134f120>,
 <Reaction R00557 at 0x1d61134f490>,
 <Reaction R00558 at 0x1d61134f540>,
 <Reaction R00565 at 0x1d61134f5f0>,
 <Reaction R00602 at 0x1d61134f6a0>,
 <Reaction R00610 at 0x1d61134f750>,
 <Reaction R00647 at 0x1d61134f800>,
 <Reaction R00654 at 0x1d61134f8b0>,
 <Reaction R00668 at 0x1d61134f960>,
 <Reaction R00670 at 0x1d61134fa10>,
 <Reaction R00673 at 0x1d61134fac0>,
 <Reaction R00678 at 0x1d61134fb70>,
 <Reaction R00685 at 0x1d61134fc20>,
 <Reaction R00691 at 0x1d61134fcd0>,
 <Reaction R00698 at 0x1d61134fd80>,
 <Reaction R00699 at 0x1d61134fe30>,
 <Reaction R00705 at 0x1d613549b20>,
 <Reaction R00713 at 0x1d613549bd0>,
 <Reaction R00715 at 0x1d613549c80>,
 <Reaction R00720 at 0x1d613549d30>,
 <Reaction R00722 at 0x1d613549de0>,
 <Reaction R00724 at 0x1d613549e90>,
 <Reaction R00736 at 0x1d613549f40>,
 <Reaction R00754 at 0x1d613549ff0>,
 <Reaction R00760 at 0x1d61354a0a0>,
 <Reaction R00765 at 0x1d61354a150>,
 <Reaction R00772 at 0x1d61354a200>,
 <Reaction R00782 at 0x1d61354a2b0>,
 <Reaction R00787 at 0x1d61354a360>,
 <Reaction R00789 at 0x1d61354a410>,
 <Reaction R00794 at 0x1d61354a4c0>,
 <Reaction R00801 at 0x1d61354a570>,
 <Reaction R00817 at 0x1d61354a620>,
 <Reaction R00818 at 0x1d61354a6d0>,
 <Reaction R00829 at 0x1d61354a780>,
 <Reaction R00833 at 0x1d61354a830>,
 <Reaction R00836 at 0x1d61354a8e0>,
 <Reaction R00839 at 0x1d61354a990>,
 <Reaction R00847 at 0x1d61354aa40>,
 <Reaction R00848 at 0x1d61354aaf0>,
 <Reaction R00856 at 0x1d61354aba0>,
 <Reaction R00872 at 0x1d61354ac50>,
 <Reaction R00885 at 0x1d61354ad00>,
 <Reaction R00894 at 0x1d61354adb0>,
 <Reaction R00899 at 0x1d61354ae60>,
 <Reaction R00900 at 0x1d61354af10>,
 <Reaction R00904 at 0x1d61354afc0>,
 <Reaction R00908 at 0x1d61354b070>,
 <Reaction R00918 at 0x1d61354b120>,
 <Reaction R00922 at 0x1d61354b1d0>,
 <Reaction R00925 at 0x1d61354b280>,
 <Reaction R00926 at 0x1d61354b330>,
 <Reaction R00927 at 0x1d61354b3e0>,
 <Reaction R00935 at 0x1d61354b490>,
 <Reaction R00942 at 0x1d61354b540>,
 <Reaction R00943 at 0x1d61354b5f0>,
 <Reaction R00944 at 0x1d61354b6a0>,
 <Reaction R00955 at 0x1d61354b750>,
 <Reaction R00962 at 0x1d61354b800>,
 <Reaction R00964 at 0x1d61354b8b0>,
 <Reaction R00966 at 0x1d61354b960>,
 <Reaction R00967 at 0x1d61354ba10>,
 <Reaction R00968 at 0x1d61354bac0>,
 <Reaction R00970 at 0x1d61354bb70>,
 <Reaction R00974 at 0x1d61354bc20>,
 <Reaction R00982 at 0x1d61354bcd0>,
 <Reaction R00987 at 0x1d61354bd80>,
 <Reaction R00994 at 0x1d61354be30>,
 <Reaction R00996 at 0x1d61354bee0>,
 <Reaction R00997 at 0x1d6136fc050>,
 <Reaction R00999 at 0x1d6136fc100>,
 <Reaction R01010 at 0x1d6136fc1b0>,
 <Reaction R01011 at 0x1d6136fc260>,
 <Reaction R01030 at 0x1d6136fc310>,
 <Reaction R01041 at 0x1d6136fc3c0>,
 <Reaction R01054 at 0x1d6136fc470>,
 <Reaction R01064 at 0x1d6136fc520>,
 <Reaction R01074 at 0x1d6136fc5d0>,
 <Reaction R01078 at 0x1d6136fc680>,
 <Reaction R01087 at 0x1d6136fc730>,
 <Reaction R01092 at 0x1d6136fc7e0>,
 <Reaction R01100 at 0x1d6136fc890>,
 <Reaction R01101 at 0x1d6136fc940>,
 <Reaction R01103 at 0x1d6136fc9f0>,
 <Reaction R01104 at 0x1d6136fcaa0>,
 <Reaction R01123 at 0x1d6136fcb50>,
 <Reaction R01157 at 0x1d6136fcc00>,
 <Reaction R01159 at 0x1d6136fccb0>,
 <Reaction R01167 at 0x1d6136fcd60>,
 <Reaction R01168 at 0x1d6136fce10>,
 <Reaction R01175 at 0x1d6136fcec0>,
 <Reaction R01177 at 0x1d6136fcf70>,
 <Reaction R01183 at 0x1d6136fd020>,
 <Reaction R01185 at 0x1d6136fd0d0>,
 <Reaction R01186 at 0x1d6136fd180>,
 <Reaction R01187 at 0x1d6136fd230>,
 <Reaction R01194 at 0x1d6136fd2e0>,
 <Reaction R01209 at 0x1d6136fd390>,
 <Reaction R01216 at 0x1d6136fd440>,
 <Reaction R01220 at 0x1d6136fd4f0>,
 <Reaction R01221 at 0x1d6136fd5a0>,
 <Reaction R01224 at 0x1d6136fd650>,
 <Reaction R01226 at 0x1d6136fd700>,
 <Reaction R01243 at 0x1d6136fd7b0>,
 <Reaction R01255 at 0x1d6136fd860>,
 <Reaction R01268 at 0x1d6136fd910>,
 <Reaction R01273 at 0x1d6136fd9c0>,
 <Reaction R01274 at 0x1d6136fda70>,
 <Reaction R01279 at 0x1d6136fdb20>,
 <Reaction R01280 at 0x1d6136fdbd0>,
 <Reaction R01285 at 0x1d6136fdc80>,
 <Reaction R01288 at 0x1d6136fdd30>,
 <Reaction R01289 at 0x1d6136fdde0>,
 <Reaction R01293 at 0x1d6136fde90>,
 <Reaction R01298 at 0x1d6136fdf40>,
 <Reaction R01329 at 0x1d6136fdff0>,
 <Reaction R01334 at 0x1d6136fe0a0>,
 <Reaction R01353 at 0x1d6136fe150>,
 <Reaction R01354 at 0x1d6136fe200>,
 <Reaction R01357 at 0x1d6136fe2b0>,
 <Reaction R01360 at 0x1d6136fe360>,
 <Reaction R01361 at 0x1d6136fe410>,
 <Reaction R01364 at 0x1d6136fe4c0>,
 <Reaction R01366 at 0x1d6136fe570>,
 <Reaction R01372 at 0x1d6136fe620>,
 <Reaction R01394 at 0x1d6136fe6d0>,
 <Reaction R01411 at 0x1d6136fe780>,
 <Reaction R01419 at 0x1d6136fe830>,
 <Reaction R01421 at 0x1d6136fe8e0>,
 <Reaction R01424 at 0x1d6136fe990>,
 <Reaction R01459 at 0x1d6136fea40>,
 <Reaction R01465 at 0x1d6136feaf0>,
 <Reaction R01470 at 0x1d6136feba0>,
 <Reaction R01482 at 0x1d6136fec50>,
 <Reaction R01488 at 0x1d6136fed00>,
 <Reaction R01492 at 0x1d6136fedb0>,
 <Reaction R01504 at 0x1d6136fee60>,
 <Reaction R01505 at 0x1d6136fef10>,
 <Reaction R01515 at 0x1d6136fefc0>,
 <Reaction R01542 at 0x1d6136ff070>,
 <Reaction R01548 at 0x1d6136ff120>,
 <Reaction R01549 at 0x1d6136ff1d0>,
 <Reaction R01560 at 0x1d6136ff280>,
 <Reaction R01569 at 0x1d6136ff330>,
 <Reaction R01570 at 0x1d6136ff3e0>,
 <Reaction R01613 at 0x1d6136ff490>,
 <Reaction R01631 at 0x1d6136ff540>,
 <Reaction R01639 at 0x1d6136ff5f0>,
 <Reaction R01647 at 0x1d6136ff6a0>,
 <Reaction R01648 at 0x1d6136ff750>,
 <Reaction R01654 at 0x1d6136ff800>,
 <Reaction R01655 at 0x1d6136ff8b0>,
 <Reaction R01658 at 0x1d6136ff960>,
 <Reaction R01662 at 0x1d6136ffa10>,
 <Reaction R01664 at 0x1d6136ffac0>,
 <Reaction R01676 at 0x1d6136ffb70>,
 <Reaction R01686 at 0x1d6136ffc20>,
 <Reaction R01698 at 0x1d6136ffcd0>,
 <Reaction R01716 at 0x1d6136ffd80>,
 <Reaction R01717 at 0x1d6136ffe30>,
 <Reaction R01724 at 0x1d6136ffee0>,
 <Reaction R01745 at 0x1d61374c050>,
 <Reaction R01751 at 0x1d61374c100>,
 <Reaction R01752 at 0x1d61374c1b0>,
 <Reaction R01764 at 0x1d61374c260>,
 <Reaction R01768 at 0x1d61374c310>,
 <Reaction R01818 at 0x1d61374c3c0>,
 <Reaction R01837 at 0x1d61374c470>,
 <Reaction R01856 at 0x1d61374c520>,
 <Reaction R01859 at 0x1d61374c5d0>,
 <Reaction R01878 at 0x1d61374c680>,
 <Reaction R01880 at 0x1d61374c730>,
 <Reaction R01884 at 0x1d61374c7e0>,
 <Reaction R01902 at 0x1d61374c890>,
 <Reaction R01906 at 0x1d61374c940>,
 <Reaction R01920 at 0x1d61374c9f0>,
 <Reaction R01931 at 0x1d61374caa0>,
 <Reaction R01933 at 0x1d61374cb50>,
 <Reaction R01942 at 0x1d61374cc00>,
 <Reaction R01968 at 0x1d61374ccb0>,
 <Reaction R01969 at 0x1d61374cd60>,
 <Reaction R01975 at 0x1d61374ce10>,
 <Reaction R01978 at 0x1d61374cec0>,
 <Reaction R01983 at 0x1d61374cf70>,
 <Reaction R01986 at 0x1d61374d020>,
 <Reaction R01989 at 0x1d61374d0d0>,
 <Reaction R02003 at 0x1d61374d180>,
 <Reaction R02047 at 0x1d61374d230>,
 <Reaction R02059 at 0x1d61374d2e0>,
 <Reaction R02061 at 0x1d61374d390>,
 <Reaction R02065 at 0x1d61374d440>,
 <Reaction R02080 at 0x1d61374d4f0>,
 <Reaction R02088 at 0x1d61374d5a0>,
 <Reaction R02091 at 0x1d61374d650>,
 <Reaction R02096 at 0x1d61374d700>,
 <Reaction R02097 at 0x1d61374d7b0>,
 <Reaction R02102 at 0x1d61374d860>,
 <Reaction R02103 at 0x1d61374d910>,
 <Reaction R02106 at 0x1d61374d9c0>,
 <Reaction R02124 at 0x1d61374da70>,
 <Reaction R02133 at 0x1d61374db20>,
 <Reaction R02173 at 0x1d61374dbd0>,
 <Reaction R02216 at 0x1d61374dc80>,
 <Reaction R02222 at 0x1d61374dd30>,
 <Reaction R02231 at 0x1d61374dde0>,
 <Reaction R02237 at 0x1d61374de90>,
 <Reaction R02262 at 0x1d61374df40>,
 <Reaction R02269 at 0x1d61374dff0>,
 <Reaction R02272 at 0x1d61374e0a0>,
 <Reaction R02279 at 0x1d61374e150>,
 <Reaction R02288 at 0x1d61374e200>,
 <Reaction R02294 at 0x1d61374e2b0>,
 <Reaction R02295 at 0x1d61374e360>,
 <Reaction R02300 at 0x1d61374e410>,
 <Reaction R02301 at 0x1d61374e4c0>,
 <Reaction R02323 at 0x1d61374e570>,
 <Reaction R02327 at 0x1d61374e620>,
 <Reaction R02328 at 0x1d61374e6d0>,
 <Reaction R02332 at 0x1d61374e780>,
 <Reaction R02354 at 0x1d61374e830>,
 <Reaction R02355 at 0x1d61374e8e0>,
 <Reaction R02356 at 0x1d61374e990>,
 <Reaction R02371 at 0x1d61374ea40>,
 <Reaction R02372 at 0x1d61374eaf0>,
 <Reaction R02377 at 0x1d61374eba0>,
 <Reaction R02382 at 0x1d61374ec50>,
 <Reaction R02387 at 0x1d61374ed00>,
 <Reaction R02396 at 0x1d61374edb0>,
 <Reaction R02404 at 0x1d61374ee60>,
 <Reaction R02408 at 0x1d61374ef10>,
 <Reaction R02422 at 0x1d61374efc0>,
 <Reaction R02424 at 0x1d61374f070>,
 <Reaction R02425 at 0x1d61374f120>,
 <Reaction R02430 at 0x1d61374f1d0>,
 <Reaction R02454 at 0x1d61374f280>,
 <Reaction R02457 at 0x1d61374f330>,
 <Reaction R02472 at 0x1d61374f3e0>,
 <Reaction R02473 at 0x1d61374f490>,
 <Reaction R02484 at 0x1d61374f540>,
 <Reaction R02485 at 0x1d61374f5f0>,
 <Reaction R02487 at 0x1d61374f6a0>,
 <Reaction R02499 at 0x1d61374f750>,
 <Reaction R02508 at 0x1d61374f800>,
 <Reaction R02519 at 0x1d61374f8b0>,
 <Reaction R02520 at 0x1d61374f960>,
 <Reaction R02521 at 0x1d61374fa10>,
 <Reaction R02529 at 0x1d61374fac0>,
 <Reaction R02532 at 0x1d61374fb70>,
 <Reaction R02536 at 0x1d61374fc20>,
 <Reaction R02539 at 0x1d61374fcd0>,
 <Reaction R02540 at 0x1d61374fd80>,
 <Reaction R02545 at 0x1d61374fe30>,
 <Reaction R02549 at 0x1d61374fee0>,
 <Reaction R02556 at 0x1d6138b8050>,
 <Reaction R02557 at 0x1d6138b8100>,
 <Reaction R02565 at 0x1d6138b81b0>,
 <Reaction R02566 at 0x1d6138b8260>,
 <Reaction R02613 at 0x1d6138b8310>,
 <Reaction R02644 at 0x1d6138b83c0>,
 <Reaction R02668 at 0x1d6138b8470>,
 <Reaction R02670 at 0x1d6138b8520>,
 <Reaction R02671 at 0x1d6138b85d0>,
 <Reaction R02672 at 0x1d6138b8680>,
 <Reaction R02678 at 0x1d6138b8730>,
 <Reaction R02701 at 0x1d6138b87e0>,
 <Reaction R02706 at 0x1d6138b8890>,
 <Reaction R02720 at 0x1d6138b8940>,
 <Reaction R02748 at 0x1d6138b89f0>,
 <Reaction R02752 at 0x1d6138b8aa0>,
 <Reaction R02777 at 0x1d6138b8b50>,
 <Reaction R02778 at 0x1d6138b8c00>,
 <Reaction R02782 at 0x1d6138b8cb0>,
 <Reaction R02788 at 0x1d6138b8d60>,
 <Reaction R02807 at 0x1d6138b8e10>,
 <Reaction R02840 at 0x1d6138b8ec0>,
 <Reaction R02853 at 0x1d6138b8f70>,
 <Reaction R02855 at 0x1d6138b9020>,
 <Reaction R02857 at 0x1d6138b90d0>,
 <Reaction R02858 at 0x1d6138b9180>,
 <Reaction R02864 at 0x1d6138b9230>,
 <Reaction R02869 at 0x1d6138b92e0>,
 <Reaction R02894 at 0x1d6138b9390>,
 <Reaction R02908 at 0x1d6138b9440>,
 <Reaction R02912 at 0x1d6138b94f0>,
 <Reaction R02914 at 0x1d6138b95a0>,
 <Reaction R02919 at 0x1d6138b9650>,
 <Reaction R02922 at 0x1d6138b9700>,
 <Reaction R02923 at 0x1d6138b97b0>,
 <Reaction R02926 at 0x1d6138b9860>,
 <Reaction R02933 at 0x1d6138b9910>,
 <Reaction R02940 at 0x1d6138b99c0>,
 <Reaction R02946 at 0x1d6138b9a70>,
 <Reaction R02957 at 0x1d6138b9b20>,
 <Reaction R02971 at 0x1d6138b9bd0>,
 <Reaction R02984 at 0x1d6138b9c80>,
 <Reaction R02991 at 0x1d6138b9d30>,
 <Reaction R03004 at 0x1d6138b9de0>,
 <Reaction R03005 at 0x1d6138b9e90>,
 <Reaction R03014 at 0x1d6138b9f40>,
 <Reaction R03018 at 0x1d6138b9ff0>,
 <Reaction R03024 at 0x1d6138ba0a0>,
 <Reaction R03026 at 0x1d6138ba150>,
 <Reaction R03033 at 0x1d6138ba200>,
 <Reaction R03035 at 0x1d6138ba2b0>,
 <Reaction R03037 at 0x1d6138ba360>,
 <Reaction R03051 at 0x1d6138ba410>,
 <Reaction R03055 at 0x1d6138ba4c0>,
 <Reaction R03065 at 0x1d6138ba570>,
 <Reaction R03066 at 0x1d6138ba620>,
 <Reaction R03067 at 0x1d6138ba6d0>,
 <Reaction R03088 at 0x1d6138ba780>,
 <Reaction R03089 at 0x1d6138ba830>,
 <Reaction R03090 at 0x1d6138ba8e0>,
 <Reaction R03096 at 0x1d6138ba990>,
 <Reaction R03105 at 0x1d6138baa40>,
 <Reaction R03106 at 0x1d6138baaf0>,
 <Reaction R03119 at 0x1d6138baba0>,
 <Reaction R03157 at 0x1d6138bac50>,
 <Reaction R03163 at 0x1d6138bad00>,
 <Reaction R03165 at 0x1d6138badb0>,
 <Reaction R03180 at 0x1d6138bae60>,
 <Reaction R03182 at 0x1d6138baf10>,
 <Reaction R03184 at 0x1d6138bafc0>,
 <Reaction R03194 at 0x1d6138bb070>,
 <Reaction R03197 at 0x1d6138bb120>,
 <Reaction R03209 at 0x1d6138bb1d0>,
 <Reaction R03210 at 0x1d6138bb280>,
 <Reaction R03217 at 0x1d6138bb330>,
 <Reaction R03222 at 0x1d6138bb3e0>,
 <Reaction R03223 at 0x1d6138bb490>,
 <Reaction R03231 at 0x1d6138bb540>,
 <Reaction R03234 at 0x1d6138bb5f0>,
 <Reaction R03236 at 0x1d6138bb6a0>,
 <Reaction R03237 at 0x1d6138bb750>,
 <Reaction R03238 at 0x1d6138bb800>,
 <Reaction R03239 at 0x1d6138bb8b0>,
 <Reaction R03260 at 0x1d6138bb960>,
 <Reaction R03269 at 0x1d6138bba10>,
 <Reaction R03276 at 0x1d6138bbac0>,
 <Reaction R03283 at 0x1d6138bbb70>,
 <Reaction R03291 at 0x1d6138bbc20>,
 <Reaction R03293 at 0x1d6138bbcd0>,
 <Reaction R03307 at 0x1d6138bbd80>,
 <Reaction R03319 at 0x1d6138bbe30>,
 <Reaction R03327 at 0x1d6138bbee0>,
 <Reaction R03346 at 0x1d613908050>,
 <Reaction R03347 at 0x1d613908100>,
 <Reaction R03348 at 0x1d6139081b0>,
 <Reaction R03371 at 0x1d613908260>,
 <Reaction R03387 at 0x1d613908310>,
 <Reaction R03408 at 0x1d6139083c0>,
 <Reaction R03409 at 0x1d613908470>,
 <Reaction R03458 at 0x1d613908520>,
 <Reaction R03459 at 0x1d6139085d0>,
 <Reaction R03470 at 0x1d613908680>,
 <Reaction R03471 at 0x1d613908730>,
 <Reaction R03472 at 0x1d6139087e0>,
 <Reaction R03503 at 0x1d613908890>,
 <Reaction R03504 at 0x1d613908940>,
 <Reaction R03530 at 0x1d6139089f0>,
 <Reaction R03531 at 0x1d613908aa0>,
 <Reaction R03544 at 0x1d613908b50>,
 <Reaction R03549 at 0x1d613908c00>,
 <Reaction R03595 at 0x1d613908cb0>,
 <Reaction R03601 at 0x1d613908d60>,
 <Reaction R03630 at 0x1d613908e10>,
 <Reaction R03632 at 0x1d613908ec0>,
 <Reaction R03634 at 0x1d613908f70>,
 <Reaction R03743 at 0x1d613909020>,
 <Reaction R03751 at 0x1d6139090d0>,
 <Reaction R03774 at 0x1d613909180>,
 <Reaction R03777 at 0x1d613909230>,
 <Reaction R03778 at 0x1d6139092e0>,
 <Reaction R03824 at 0x1d613909390>,
 <Reaction R03845 at 0x1d613909440>,
 <Reaction R03857 at 0x1d6139094f0>,
 <Reaction R03858 at 0x1d6139095a0>,
 <Reaction R03869 at 0x1d613909650>,
 <Reaction R03877 at 0x1d613909700>,
 <Reaction R03884 at 0x1d6139097b0>,
 <Reaction R03893 at 0x1d613909860>,
 <Reaction R03896 at 0x1d613909910>,
 <Reaction R03898 at 0x1d6139099c0>,
 <Reaction R03936 at 0x1d613909a70>,
 <Reaction R03943 at 0x1d613909b20>,
 <Reaction R03947 at 0x1d613909bd0>,
 <Reaction R03948 at 0x1d613909c80>,
 <Reaction R03950 at 0x1d613909d30>,
 <Reaction R03955 at 0x1d613909de0>,
 <Reaction R03970 at 0x1d613909e90>,
 <Reaction R03971 at 0x1d613909f40>,
 <Reaction R03980 at 0x1d613909ff0>,
 <Reaction R03982 at 0x1d61390a0a0>,
 <Reaction R03990 at 0x1d61390a150>,
 <Reaction R03991 at 0x1d61390a200>,
 <Reaction R04000 at 0x1d61390a2b0>,
 <Reaction R04025 at 0x1d61390a360>,
 <Reaction R04030 at 0x1d61390a410>,
 <Reaction R04031 at 0x1d61390a4c0>,
 <Reaction R04049 at 0x1d61390a570>,
 <Reaction R04065 at 0x1d61390a620>,
 <Reaction R04095 at 0x1d61390a6d0>,
 <Reaction R04112 at 0x1d61390a780>,
 <Reaction R04137 at 0x1d61390a830>,
 <Reaction R04138 at 0x1d61390a8e0>,
 <Reaction R04148 at 0x1d61390a990>,
 <Reaction R04150 at 0x1d61390aa40>,
 <Reaction R04163 at 0x1d61390aaf0>,
 <Reaction R04170 at 0x1d61390aba0>,
 <Reaction R04172 at 0x1d61390ac50>,
 <Reaction R04188 at 0x1d61390ad00>,
 <Reaction R04203 at 0x1d61390adb0>,
 <Reaction R04204 at 0x1d61390ae60>,
 <Reaction R04206 at 0x1d61390af10>,
 <Reaction R04218 at 0x1d61390afc0>,
 <Reaction R04221 at 0x1d61390b070>,
 <Reaction R04224 at 0x1d61390b120>,
 <Reaction R04230 at 0x1d61390b1d0>,
 <Reaction R04231 at 0x1d61390b280>,
 <Reaction R04257 at 0x1d61390b330>,
 <Reaction R04258 at 0x1d61390b3e0>,
 <Reaction R04292 at 0x1d61390b490>,
 <Reaction R04300 at 0x1d61390b540>,
 <Reaction R04306 at 0x1d61390b5f0>,
 <Reaction R04318 at 0x1d61390b6a0>,
 <Reaction R04326 at 0x1d61390b750>,
 <Reaction R04378 at 0x1d61390b800>,
 <Reaction R04379 at 0x1d61390b8b0>,
 <Reaction R04391 at 0x1d61390b960>,
 <Reaction R04420 at 0x1d61390ba10>,
 <Reaction R04444 at 0x1d61390bac0>,
 <Reaction R04445 at 0x1d61390bb70>,
 <Reaction R04457 at 0x1d61390bc20>,
 <Reaction R04464 at 0x1d61390bcd0>,
 <Reaction R04482 at 0x1d61390bd80>,
 <Reaction R04489 at 0x1d61390be30>,
 <Reaction R04506 at 0x1d61390bee0>,
 <Reaction R04509 at 0x1d613964050>,
 <Reaction R04546 at 0x1d613964100>,
 <Reaction R04547 at 0x1d6139641b0>,
 <Reaction R04573 at 0x1d613964260>,
 <Reaction R04592 at 0x1d613964310>,
 <Reaction R04617 at 0x1d6139643c0>,
 <Reaction R04620 at 0x1d613964470>,
 <Reaction R04639 at 0x1d613964520>,
 <Reaction R04674 at 0x1d6139645d0>,
 <Reaction R04678 at 0x1d613964680>,
 <Reaction R04734 at 0x1d613964730>,
 <Reaction R04737 at 0x1d6139647e0>,
 <Reaction R04738 at 0x1d613964890>,
 <Reaction R04739 at 0x1d613964940>,
 <Reaction R04740 at 0x1d6139649f0>,
 <Reaction R04741 at 0x1d613964aa0>,
 <Reaction R04742 at 0x1d613964b50>,
 <Reaction R04743 at 0x1d613964c00>,
 <Reaction R04744 at 0x1d613964cb0>,
 <Reaction R04745 at 0x1d613964d60>,
 <Reaction R04746 at 0x1d613964e10>,
 <Reaction R04747 at 0x1d613964ec0>,
 <Reaction R04748 at 0x1d613964f70>,
 <Reaction R04749 at 0x1d613965020>,
 <Reaction R04751 at 0x1d6139650d0>,
 <Reaction R04754 at 0x1d613965180>,
 <Reaction R04770 at 0x1d613965230>,

In [37]:
model.reactions.get_by_id('R02300')

In [36]:
model.reactions.get_by_id('R02404')

In [4]:
model.reactions

[<Reaction R00004 at 0x1d610b90ec0>,
 <Reaction R00005 at 0x1d610ca82d0>,
 <Reaction R00006 at 0x1d610ca8410>,
 <Reaction R00009 at 0x1d610927100>,
 <Reaction R00013 at 0x1d610927230>,
 <Reaction R00022 at 0x1d6109232f0>,
 <Reaction R00025 at 0x1d6108b7570>,
 <Reaction R00028 at 0x1d6108b7680>,
 <Reaction R00036 at 0x1d61094fa50>,
 <Reaction R00066 at 0x1d61094fb50>,
 <Reaction R00069 at 0x1d61097d4f0>,
 <Reaction R00084 at 0x1d61097d5e0>,
 <Reaction R00089 at 0x1d610cc3af0>,
 <Reaction R00093 at 0x1d610cc3bd0>,
 <Reaction R00094 at 0x1d610cb0460>,
 <Reaction R00103 at 0x1d610b2c710>,
 <Reaction R00104 at 0x1d610b2c7d0>,
 <Reaction R00106 at 0x1d610b54680>,
 <Reaction R00111 at 0x1d610b54730>,
 <Reaction R00112 at 0x1d610b547e0>,
 <Reaction R00114 at 0x1d610b54890>,
 <Reaction R00115 at 0x1d610b54940>,
 <Reaction R00118 at 0x1d610b549f0>,
 <Reaction R00130 at 0x1d610b54aa0>,
 <Reaction R00131 at 0x1d610b54b50>,
 <Reaction R00132 at 0x1d610b54c00>,
 <Reaction R00137 at 0x1d610b54cb0>,
 <Reaction R00139 at 0x1d610b54d60>,
 <Reaction R00161 at 0x1d610b54e10>,
 <Reaction R00177 at 0x1d610b54ec0>,
 <Reaction R00178 at 0x1d610b54f70>,
 <Reaction R00189 at 0x1d610b55020>,
 <Reaction R00192 at 0x1d610b550d0>,
 <Reaction R00217 at 0x1d610b55180>,
 <Reaction R00220 at 0x1d610b55230>,
 <Reaction R00253 at 0x1d610b552e0>,
 <Reaction R00254 at 0x1d610b55390>,
 <Reaction R00257 at 0x1d610b55440>,
 <Reaction R00264 at 0x1d610b554f0>,
 <Reaction R00272 at 0x1d610b555a0>,
 <Reaction R00275 at 0x1d610b55650>,
 <Reaction R00277 at 0x1d610b55700>,
 <Reaction R00278 at 0x1d610b557b0>,
 <Reaction R00286 at 0x1d610b55860>,
 <Reaction R00306 at 0x1d610b55910>,
 <Reaction R00310 at 0x1d610b559c0>,
 <Reaction R00321 at 0x1d610b55a70>,
 <Reaction R00335 at 0x1d610b55b20>,
 <Reaction R00354 at 0x1d610b55bd0>,
 <Reaction R00357 at 0x1d610b55c80>,
 <Reaction R00366 at 0x1d610b55d30>,
 <Reaction R00371 at 0x1d610b55de0>,
 <Reaction R00372 at 0x1d610b55e90>,
 <Reaction R00418 at 0x1d610b55f40>,
 <Reaction R00424 at 0x1d610b55ff0>,
 <Reaction R00425 at 0x1d610b560a0>,
 <Reaction R00428 at 0x1d610b56150>,
 <Reaction R00429 at 0x1d610b56200>,
 <Reaction R00434 at 0x1d610b562b0>,
 <Reaction R00457 at 0x1d610b56360>,
 <Reaction R00470 at 0x1d610b56410>,
 <Reaction R00471 at 0x1d610b564c0>,
 <Reaction R00475 at 0x1d610b56570>,
 <Reaction R00481 at 0x1d610b56620>,
 <Reaction R00489 at 0x1d610b566d0>,
 <Reaction R00490 at 0x1d610b56780>,
 <Reaction R00491 at 0x1d610b56830>,
 <Reaction R00494 at 0x1d610b568e0>,
 <Reaction R00505 at 0x1d610b56990>,
 <Reaction R00513 at 0x1d610b56a40>,
 <Reaction R00516 at 0x1d610b56af0>,
 <Reaction R00517 at 0x1d610b56ba0>,
 <Reaction R00519 at 0x1d610b56c50>,
 <Reaction R00524 at 0x1d610b56d00>,
 <Reaction R00549 at 0x1d610b56db0>,
 <Reaction R00551 at 0x1d610b56e60>,
 <Reaction R00552 at 0x1d610b56f10>,
 <Reaction R00557 at 0x1d610b56fc0>,
 <Reaction R00558 at 0x1d610b57070>,
 <Reaction R00565 at 0x1d610b57120>,
 <Reaction R00602 at 0x1d610b571d0>,
 <Reaction R00610 at 0x1d610b57280>,
 <Reaction R00647 at 0x1d610b57330>,
 <Reaction R00654 at 0x1d610b573e0>,
 <Reaction R00668 at 0x1d610b57490>,
 <Reaction R00670 at 0x1d610b57540>,
 <Reaction R00673 at 0x1d610b575f0>,
 <Reaction R00678 at 0x1d610b576a0>,
 <Reaction R00685 at 0x1d610b57750>,
 <Reaction R00691 at 0x1d610b57800>,
 <Reaction R00698 at 0x1d610b578b0>,
 <Reaction R00699 at 0x1d610b57960>,
 <Reaction R00705 at 0x1d610b57a10>,
 <Reaction R00713 at 0x1d610b57ac0>,
 <Reaction R00715 at 0x1d610b57b70>,
 <Reaction R00720 at 0x1d610b57c20>,
 <Reaction R00722 at 0x1d610b57cd0>,
 <Reaction R00724 at 0x1d610b57d80>,
 <Reaction R00736 at 0x1d610b57e30>,
 <Reaction R00754 at 0x1d610b57ee0>,
 <Reaction R00760 at 0x1d610d3c050>,
 <Reaction R00765 at 0x1d610d3c100>,
 <Reaction R00772 at 0x1d610d3c1b0>,
 <Reaction R00782 at 0x1d610d3c260>,
 <Reaction R00787 at 0x1d610d3c310>,
 <Reaction R00789 at 0x1d610d3c3c0>,
 <Reaction R00794 at 0x1d610d3c470>,
 <Reaction R00801 at 0x1d610d3c520>,
 <Reaction R00817 at 0x1d610d3c5d0>,
 <Reaction R00818 at 0x1d610d3c680>,
 <Reaction R00829 at 0x1d610d3c730>,
 <Reaction R00833 at 0x1d610d3c7e0>,
 <Reaction R00836 at 0x1d610d3c890>,
 <Reaction R00839 at 0x1d610d3c940>,
 <Reaction R00847 at 0x1d610d3c9f0>,
 <Reaction R00848 at 0x1d610d3caa0>,
 <Reaction R00856 at 0x1d610d3cb50>,
 <Reaction R00872 at 0x1d610d3cc00>,
 <Reaction R00885 at 0x1d610d3ccb0>,
 <Reaction R00894 at 0x1d610d3cd60>,
 <Reaction R00899 at 0x1d610d3ce10>,
 <Reaction R00900 at 0x1d610d3cec0>,
 <Reaction R00904 at 0x1d610d3cf70>,
 <Reaction R00908 at 0x1d610d3d020>,
 <Reaction R00918 at 0x1d610d3d0d0>,
 <Reaction R00922 at 0x1d610d3d180>,
 <Reaction R00925 at 0x1d610d3d230>,
 <Reaction R00926 at 0x1d610d3d2e0>,
 <Reaction R00927 at 0x1d610d3d390>,
 <Reaction R00935 at 0x1d610d3d440>,
 <Reaction R00942 at 0x1d610d3d4f0>,
 <Reaction R00943 at 0x1d610d3d5a0>,
 <Reaction R00944 at 0x1d610d3d650>,
 <Reaction R00955 at 0x1d610d3d700>,
 <Reaction R00962 at 0x1d610d3d7b0>,
 <Reaction R00964 at 0x1d610d3d860>,
 <Reaction R00966 at 0x1d610d3d910>,
 <Reaction R00967 at 0x1d610d3d9c0>,
 <Reaction R00968 at 0x1d610d3da70>,
 <Reaction R00970 at 0x1d610d3db20>,
 <Reaction R00974 at 0x1d610d3dbd0>,
 <Reaction R00982 at 0x1d610d3dc80>,
 <Reaction R00987 at 0x1d610d3dd30>,
 <Reaction R00994 at 0x1d610d3dde0>,
 <Reaction R00996 at 0x1d610d3de90>,
 <Reaction R00997 at 0x1d610d3df40>,
 <Reaction R00999 at 0x1d610d3dff0>,
 <Reaction R01010 at 0x1d610d3e0a0>,
 <Reaction R01011 at 0x1d610d3e150>,
 <Reaction R01030 at 0x1d610d3e200>,
 <Reaction R01041 at 0x1d610d3e2b0>,
 <Reaction R01054 at 0x1d610d3e360>,
 <Reaction R01064 at 0x1d610d3e410>,
 <Reaction R01074 at 0x1d610d3e4c0>,
 <Reaction R01078 at 0x1d610d3e570>,
 <Reaction R01087 at 0x1d610d3e620>,
 <Reaction R01092 at 0x1d610d3e6d0>,
 <Reaction R01100 at 0x1d610d3e780>,
 <Reaction R01101 at 0x1d610d3e830>,
 <Reaction R01103 at 0x1d610d3e8e0>,
 <Reaction R01104 at 0x1d610d3e990>,
 <Reaction R01123 at 0x1d610d3ea40>,
 <Reaction R01157 at 0x1d610d3eaf0>,
 <Reaction R01159 at 0x1d610d3eba0>,
 <Reaction R01167 at 0x1d610d3ec50>,
 <Reaction R01168 at 0x1d610d3ed00>,
 <Reaction R01175 at 0x1d610d3edb0>,
 <Reaction R01177 at 0x1d610d3ee60>,
 <Reaction R01183 at 0x1d610d3ef10>,
 <Reaction R01185 at 0x1d610d3efc0>,
 <Reaction R01186 at 0x1d610d3f070>,
 <Reaction R01187 at 0x1d610d3f120>,
 <Reaction R01194 at 0x1d610d3f1d0>,
 <Reaction R01209 at 0x1d610d3f280>,
 <Reaction R01216 at 0x1d610d3f330>,
 <Reaction R01220 at 0x1d610d3f3e0>,
 <Reaction R01221 at 0x1d610d3f490>,
 <Reaction R01224 at 0x1d610d3f540>,
 <Reaction R01226 at 0x1d610d3f5f0>,
 <Reaction R01243 at 0x1d610d3f6a0>,
 <Reaction R01255 at 0x1d610d3f750>,
 <Reaction R01268 at 0x1d610d3f800>,
 <Reaction R01273 at 0x1d610d3f8b0>,
 <Reaction R01274 at 0x1d610d3f960>,
 <Reaction R01279 at 0x1d610d3fa10>,
 <Reaction R01280 at 0x1d610d3fac0>,
 <Reaction R01285 at 0x1d610d3fb70>,
 <Reaction R01288 at 0x1d610d3fc20>,
 <Reaction R01289 at 0x1d610d3fcd0>,
 <Reaction R01293 at 0x1d610d3fd80>,
 <Reaction R01298 at 0x1d610d3fe30>,
 <Reaction R01329 at 0x1d610d3fee0>,
 <Reaction R01334 at 0x1d610da8050>,
 <Reaction R01353 at 0x1d610da8100>,
 <Reaction R01354 at 0x1d610da81b0>,
 <Reaction R01357 at 0x1d610da8260>,
 <Reaction R01360 at 0x1d610da8310>,
 <Reaction R01361 at 0x1d610da83c0>,
 <Reaction R01364 at 0x1d610da8470>,
 <Reaction R01366 at 0x1d610da8520>,
 <Reaction R01372 at 0x1d610da85d0>,
 <Reaction R01394 at 0x1d610da8680>,
 <Reaction R01411 at 0x1d610da8730>,
 <Reaction R01419 at 0x1d610da87e0>,
 <Reaction R01421 at 0x1d610da8890>,
 <Reaction R01424 at 0x1d610da8940>,
 <Reaction R01459 at 0x1d610da89f0>,
 <Reaction R01465 at 0x1d610da8aa0>,
 <Reaction R01470 at 0x1d610da8b50>,
 <Reaction R01482 at 0x1d610da8c00>,
 <Reaction R01488 at 0x1d610da8cb0>,
 <Reaction R01492 at 0x1d610da8d60>,
 <Reaction R01504 at 0x1d610da8e10>,
 <Reaction R01505 at 0x1d610da8ec0>,
 <Reaction R01515 at 0x1d610da8f70>,
 <Reaction R01542 at 0x1d610da9020>,
 <Reaction R01548 at 0x1d610da90d0>,
 <Reaction R01549 at 0x1d610da9180>,
 <Reaction R01560 at 0x1d610da9230>,
 <Reaction R01569 at 0x1d610da92e0>,
 <Reaction R01570 at 0x1d610da9390>,
 <Reaction R01613 at 0x1d610da9440>,
 <Reaction R01631 at 0x1d610da94f0>,
 <Reaction R01639 at 0x1d610da95a0>,
 <Reaction R01647 at 0x1d610da9650>,
 <Reaction R01648 at 0x1d610da9700>,
 <Reaction R01654 at 0x1d610da97b0>,
 <Reaction R01655 at 0x1d610da9860>,
 <Reaction R01658 at 0x1d610da9910>,
 <Reaction R01662 at 0x1d610da99c0>,
 <Reaction R01664 at 0x1d610da9a70>,
 <Reaction R01676 at 0x1d610da9b20>,
 <Reaction R01686 at 0x1d610da9bd0>,
 <Reaction R01698 at 0x1d610da9c80>,
 <Reaction R01716 at 0x1d610da9d30>,
 <Reaction R01717 at 0x1d610da9de0>,
 <Reaction R01724 at 0x1d610da9e90>,
 <Reaction R01745 at 0x1d610da9f40>,
 <Reaction R01751 at 0x1d610da9ff0>,
 <Reaction R01752 at 0x1d610daa0a0>,
 <Reaction R01764 at 0x1d610daa150>,
 <Reaction R01768 at 0x1d610daa200>,
 <Reaction R01818 at 0x1d610daa2b0>,
 <Reaction R01837 at 0x1d610daa360>,
 <Reaction R01856 at 0x1d610daa410>,
 <Reaction R01859 at 0x1d610daa4c0>,
 <Reaction R01878 at 0x1d610daa570>,
 <Reaction R01880 at 0x1d610daa620>,
 <Reaction R01884 at 0x1d610daa6d0>,
 <Reaction R01902 at 0x1d610daa780>,
 <Reaction R01906 at 0x1d610daa830>,
 <Reaction R01920 at 0x1d610daa8e0>,
 <Reaction R01931 at 0x1d610daa990>,
 <Reaction R01933 at 0x1d610daaa40>,
 <Reaction R01942 at 0x1d610daaaf0>,
 <Reaction R01968 at 0x1d610daaba0>,
 <Reaction R01969 at 0x1d610daac50>,
 <Reaction R01975 at 0x1d610daad00>,
 <Reaction R01978 at 0x1d610daadb0>,
 <Reaction R01983 at 0x1d610daae60>,
 <Reaction R01986 at 0x1d610daaf10>,
 <Reaction R01989 at 0x1d610daafc0>,
 <Reaction R02003 at 0x1d610dab070>,
 <Reaction R02047 at 0x1d610dab120>,
 <Reaction R02059 at 0x1d610dab1d0>,
 <Reaction R02061 at 0x1d610dab280>,
 <Reaction R02065 at 0x1d610dab330>,
 <Reaction R02080 at 0x1d610dab3e0>,
 <Reaction R02088 at 0x1d610dab490>,
 <Reaction R02091 at 0x1d610dab540>,
 <Reaction R02096 at 0x1d610dab5f0>,
 <Reaction R02097 at 0x1d610dab6a0>,
 <Reaction R02102 at 0x1d610dab750>,
 <Reaction R02103 at 0x1d610dab800>,
 <Reaction R02106 at 0x1d610dab8b0>,
 <Reaction R02124 at 0x1d610dab960>,
 <Reaction R02133 at 0x1d610daba10>,
 <Reaction R02173 at 0x1d610dabac0>,
 <Reaction R02216 at 0x1d610dabb70>,
 <Reaction R02222 at 0x1d610dabc20>,
 <Reaction R02231 at 0x1d610dabcd0>,
 <Reaction R02237 at 0x1d610dabd80>,
 <Reaction R02262 at 0x1d610dabe30>,
 <Reaction R02269 at 0x1d610dabee0>,
 <Reaction R02272 at 0x1d610e0c050>,
 <Reaction R02279 at 0x1d610e0c100>,
 <Reaction R02288 at 0x1d610e0c1b0>,
 <Reaction R02294 at 0x1d610e0c260>,
 <Reaction R02295 at 0x1d610e0c310>,
 <Reaction R02300 at 0x1d610e0c3c0>,
 <Reaction R02301 at 0x1d610e0c470>,
 <Reaction R02323 at 0x1d610e0c520>,
 <Reaction R02327 at 0x1d610e0c5d0>,
 <Reaction R02328 at 0x1d610e0c680>,
 <Reaction R02332 at 0x1d610e0c730>,
 <Reaction R02354 at 0x1d610e0c7e0>,
 <Reaction R02355 at 0x1d610e0c890>,
 <Reaction R02356 at 0x1d610e0c940>,
 <Reaction R02371 at 0x1d610e0c9f0>,
 <Reaction R02372 at 0x1d610e0caa0>,
 <Reaction R02377 at 0x1d610e0cb50>,
 <Reaction R02382 at 0x1d610e0cc00>,
 <Reaction R02387 at 0x1d610e0ccb0>,
 <Reaction R02396 at 0x1d610e0cd60>,
 <Reaction R02404 at 0x1d610e0ce10>,
 <Reaction R02408 at 0x1d610e0cec0>,
 <Reaction R02422 at 0x1d610e0cf70>,
 <Reaction R02424 at 0x1d610e0d020>,
 <Reaction R02425 at 0x1d610e0d0d0>,
 <Reaction R02430 at 0x1d610e0d180>,
 <Reaction R02454 at 0x1d610e0d230>,
 <Reaction R02457 at 0x1d610e0d2e0>,
 <Reaction R02472 at 0x1d610e0d390>,
 <Reaction R02473 at 0x1d610e0d440>,
 <Reaction R02484 at 0x1d610e0d4f0>,
 <Reaction R02485 at 0x1d610e0d5a0>,
 <Reaction R02487 at 0x1d610e0d650>,
 <Reaction R02499 at 0x1d610e0d700>,
 <Reaction R02508 at 0x1d610e0d7b0>,
 <Reaction R02519 at 0x1d610e0d860>,
 <Reaction R02520 at 0x1d610e0d910>,
 <Reaction R02521 at 0x1d610e0d9c0>,
 <Reaction R02529 at 0x1d610e0da70>,
 <Reaction R02532 at 0x1d610e0db20>,
 <Reaction R02536 at 0x1d610e0dbd0>,
 <Reaction R02539 at 0x1d610e0dc80>,
 <Reaction R02540 at 0x1d610e0dd30>,
 <Reaction R02545 at 0x1d610e0dde0>,
 <Reaction R02549 at 0x1d610e0de90>,
 <Reaction R02556 at 0x1d610e0df40>,
 <Reaction R02557 at 0x1d610e0dff0>,
 <Reaction R02565 at 0x1d610e0e0a0>,
 <Reaction R02566 at 0x1d610e0e150>,
 <Reaction R02613 at 0x1d610e0e200>,
 <Reaction R02644 at 0x1d610e0e2b0>,
 <Reaction R02668 at 0x1d610e0e360>,
 <Reaction R02670 at 0x1d610e0e410>,
 <Reaction R02671 at 0x1d610e0e4c0>,
 <Reaction R02672 at 0x1d610e0e570>,
 <Reaction R02678 at 0x1d610e0e620>,
 <Reaction R02701 at 0x1d610e0e6d0>,
 <Reaction R02706 at 0x1d610e0e780>,
 <Reaction R02720 at 0x1d610e0e830>,
 <Reaction R02748 at 0x1d610e0e8e0>,
 <Reaction R02752 at 0x1d610e0e990>,
 <Reaction R02777 at 0x1d610e0ea40>,
 <Reaction R02778 at 0x1d610e0eaf0>,
 <Reaction R02782 at 0x1d610e0eba0>,
 <Reaction R02788 at 0x1d610e0ec50>,
 <Reaction R02807 at 0x1d610e0ed00>,
 <Reaction R02840 at 0x1d610e0edb0>,
 <Reaction R02853 at 0x1d610e0ee60>,
 <Reaction R02855 at 0x1d610e0ef10>,
 <Reaction R02857 at 0x1d610e0efc0>,
 <Reaction R02858 at 0x1d610e0f070>,
 <Reaction R02864 at 0x1d610e0f120>,
 <Reaction R02869 at 0x1d610e0f1d0>,
 <Reaction R02894 at 0x1d610e0f280>,
 <Reaction R02908 at 0x1d610e0f330>,
 <Reaction R02912 at 0x1d610e0f3e0>,
 <Reaction R02914 at 0x1d610e0f490>,
 <Reaction R02919 at 0x1d610e0f540>,
 <Reaction R02922 at 0x1d610e0f5f0>,
 <Reaction R02923 at 0x1d610e0f6a0>,
 <Reaction R02926 at 0x1d610e0f750>,
 <Reaction R02933 at 0x1d610e0f800>,
 <Reaction R02940 at 0x1d610e0f8b0>,
 <Reaction R02946 at 0x1d610e0f960>,
 <Reaction R02957 at 0x1d610e0fa10>,
 <Reaction R02971 at 0x1d610e0fac0>,
 <Reaction R02984 at 0x1d610e0fb70>,
 <Reaction R02991 at 0x1d610e0fc20>,
 <Reaction R03004 at 0x1d610e0fcd0>,
 <Reaction R03005 at 0x1d610e0fd80>,
 <Reaction R03014 at 0x1d610e0fe30>,
 <Reaction R03018 at 0x1d610e0fee0>,
 <Reaction R03024 at 0x1d610e74050>,
 <Reaction R03026 at 0x1d610e74100>,
 <Reaction R03033 at 0x1d610e741b0>,
 <Reaction R03035 at 0x1d610e74260>,
 <Reaction R03037 at 0x1d610e74310>,
 <Reaction R03051 at 0x1d610e743c0>,
 <Reaction R03055 at 0x1d610e74470>,
 <Reaction R03065 at 0x1d610e74520>,
 <Reaction R03066 at 0x1d610e745d0>,
 <Reaction R03067 at 0x1d610e74680>,
 <Reaction R03088 at 0x1d610e74730>,
 <Reaction R03089 at 0x1d610e747e0>,
 <Reaction R03090 at 0x1d610e74890>,
 <Reaction R03096 at 0x1d610e74940>,
 <Reaction R03105 at 0x1d610e749f0>,
 <Reaction R03106 at 0x1d610e74aa0>,
 <Reaction R03119 at 0x1d610e74b50>,
 <Reaction R03157 at 0x1d610e74c00>,
 <Reaction R03163 at 0x1d610e74cb0>,
 <Reaction R03165 at 0x1d610e74d60>,
 <Reaction R03180 at 0x1d610e74e10>,
 <Reaction R03182 at 0x1d610e74ec0>,
 <Reaction R03184 at 0x1d610e74f70>,
 <Reaction R03194 at 0x1d610e75020>,
 <Reaction R03197 at 0x1d610e750d0>,
 <Reaction R03209 at 0x1d610e75180>,
 <Reaction R03210 at 0x1d610e75230>,
 <Reaction R03217 at 0x1d610e752e0>,
 <Reaction R03222 at 0x1d610e75390>,
 <Reaction R03223 at 0x1d610e75440>,
 <Reaction R03231 at 0x1d610e754f0>,
 <Reaction R03234 at 0x1d610e755a0>,
 <Reaction R03236 at 0x1d610e75650>,
 <Reaction R03237 at 0x1d610e75700>,
 <Reaction R03238 at 0x1d610e757b0>,
 <Reaction R03239 at 0x1d610e75860>,
 <Reaction R03260 at 0x1d610e75910>,
 <Reaction R03269 at 0x1d610e759c0>,
 <Reaction R03276 at 0x1d610e75a70>,
 <Reaction R03283 at 0x1d610e75b20>,
 <Reaction R03291 at 0x1d610e75bd0>,
 <Reaction R03293 at 0x1d610e75c80>,
 <Reaction R03307 at 0x1d610e75d30>,
 <Reaction R03319 at 0x1d610e75de0>,
 <Reaction R03327 at 0x1d610e75e90>,
 <Reaction R03346 at 0x1d610e75f40>,
 <Reaction R03347 at 0x1d610e75ff0>,
 <Reaction R03348 at 0x1d610e760a0>,
 <Reaction R03371 at 0x1d610e76150>,
 <Reaction R03387 at 0x1d610e76200>,
 <Reaction R03408 at 0x1d610e762b0>,
 <Reaction R03409 at 0x1d610e76360>,
 <Reaction R03458 at 0x1d610e76410>,
 <Reaction R03459 at 0x1d610e764c0>,
 <Reaction R03470 at 0x1d610e76570>,
 <Reaction R03471 at 0x1d610e76620>,
 <Reaction R03472 at 0x1d610e766d0>,
 <Reaction R03503 at 0x1d610e76780>,
 <Reaction R03504 at 0x1d610e76830>,
 <Reaction R03530 at 0x1d610e768e0>,
 <Reaction R03531 at 0x1d610e76990>,
 <Reaction R03544 at 0x1d610e76a40>,
 <Reaction R03549 at 0x1d610e76af0>,
 <Reaction R03595 at 0x1d610e76ba0>,
 <Reaction R03601 at 0x1d610e76c50>,
 <Reaction R03630 at 0x1d610e76d00>,
 <Reaction R03632 at 0x1d610e76db0>,
 <Reaction R03634 at 0x1d610e76e60>,
 <Reaction R03743 at 0x1d610e76f10>,
 <Reaction R03751 at 0x1d610e76fc0>,
 <Reaction R03774 at 0x1d610e77070>,
 <Reaction R03777 at 0x1d610e77120>,
 <Reaction R03778 at 0x1d610e771d0>,
 <Reaction R03824 at 0x1d610e77280>,
 <Reaction R03845 at 0x1d610e77330>,
 <Reaction R03857 at 0x1d610e773e0>,
 <Reaction R03858 at 0x1d610e77490>,
 <Reaction R03869 at 0x1d610e77540>,
 <Reaction R03877 at 0x1d610e775f0>,
 <Reaction R03884 at 0x1d610e776a0>,
 <Reaction R03893 at 0x1d610e77750>,
 <Reaction R03896 at 0x1d610e77800>,
 <Reaction R03898 at 0x1d610e778b0>,
 <Reaction R03936 at 0x1d610e77960>,
 <Reaction R03943 at 0x1d610e77a10>,
 <Reaction R03947 at 0x1d610e77ac0>,
 <Reaction R03948 at 0x1d610e77b70>,
 <Reaction R03950 at 0x1d610e77c20>,
 <Reaction R03955 at 0x1d610e77cd0>,
 <Reaction R03970 at 0x1d610e77d80>,
 <Reaction R03971 at 0x1d610e77e30>,
 <Reaction R03980 at 0x1d610e77ee0>,
 <Reaction R03982 at 0x1d610ed4050>,
 <Reaction R03990 at 0x1d610ed4100>,
 <Reaction R03991 at 0x1d610ed41b0>,
 <Reaction R04000 at 0x1d610ed4260>,
 <Reaction R04025 at 0x1d610ed4310>,
 <Reaction R04030 at 0x1d610ed43c0>,
 <Reaction R04031 at 0x1d610ed4470>,
 <Reaction R04049 at 0x1d610ed4520>,
 <Reaction R04065 at 0x1d610ed45d0>,
 <Reaction R04095 at 0x1d610ed4680>,
 <Reaction R04112 at 0x1d610ed4730>,
 <Reaction R04137 at 0x1d610ed47e0>,
 <Reaction R04138 at 0x1d610ed4890>,
 <Reaction R04148 at 0x1d610ed4940>,
 <Reaction R04150 at 0x1d610ed49f0>,
 <Reaction R04163 at 0x1d610ed4aa0>,
 <Reaction R04170 at 0x1d610ed4b50>,
 <Reaction R04172 at 0x1d610ed4c00>,
 <Reaction R04188 at 0x1d610ed4cb0>,
 <Reaction R04203 at 0x1d610ed4d60>,
 <Reaction R04204 at 0x1d610ed4e10>,
 <Reaction R04206 at 0x1d610ed4ec0>,
 <Reaction R04218 at 0x1d610ed4f70>,
 <Reaction R04221 at 0x1d610ed5020>,
 <Reaction R04224 at 0x1d610ed50d0>,
 <Reaction R04230 at 0x1d610ed5180>,
 <Reaction R04231 at 0x1d610ed5230>,
 <Reaction R04257 at 0x1d610ed52e0>,
 <Reaction R04258 at 0x1d610ed5390>,
 <Reaction R04292 at 0x1d610ed5440>,
 <Reaction R04300 at 0x1d610ed54f0>,
 <Reaction R04306 at 0x1d610ed55a0>,
 <Reaction R04318 at 0x1d610ed5650>,
 <Reaction R04326 at 0x1d610ed5700>,
 <Reaction R04378 at 0x1d610ed57b0>,
 <Reaction R04379 at 0x1d610ed5860>,
 <Reaction R04391 at 0x1d610ed5910>,
 <Reaction R04420 at 0x1d610ed59c0>,
 <Reaction R04444 at 0x1d610ed5a70>,
 <Reaction R04445 at 0x1d610ed5b20>,
 <Reaction R04457 at 0x1d610ed5bd0>,
 <Reaction R04464 at 0x1d610ed5c80>,
 <Reaction R04482 at 0x1d610ed5d30>,
 <Reaction R04489 at 0x1d610ed5de0>,
 <Reaction R04506 at 0x1d610ed5e90>,
 <Reaction R04509 at 0x1d610ed5f40>,
 <Reaction R04546 at 0x1d610ed5ff0>,
 <Reaction R04547 at 0x1d610ed60a0>,
 <Reaction R04573 at 0x1d610ed6150>,
 <Reaction R04592 at 0x1d610ed6200>,
 <Reaction R04617 at 0x1d610ed62b0>,
 <Reaction R04620 at 0x1d610ed6360>,
 <Reaction R04639 at 0x1d610ed6410>,
 <Reaction R04674 at 0x1d610ed64c0>,
 <Reaction R04678 at 0x1d610ed6570>,
 <Reaction R04734 at 0x1d610ed6620>,
 <Reaction R04737 at 0x1d610ed66d0>,
 <Reaction R04738 at 0x1d610ed6780>,
 <Reaction R04739 at 0x1d610ed6830>,
 <Reaction R04740 at 0x1d610ed68e0>,
 <Reaction R04741 at 0x1d610ed6990>,
 <Reaction R04742 at 0x1d610ed6a40>,
 <Reaction R04743 at 0x1d610ed6af0>,
 <Reaction R04744 at 0x1d610ed6ba0>,
 <Reaction R04745 at 0x1d610ed6c50>,
 <Reaction R04746 at 0x1d610ed6d00>,
 <Reaction R04747 at 0x1d610ed6db0>,
 <Reaction R04748 at 0x1d610ed6e60>,
 <Reaction R04749 at 0x1d610ed6f10>,
 <Reaction R04751 at 0x1d610ed6fc0>,
 <Reaction R04754 at 0x1d610ed7070>,
 <Reaction R04770 at 0x1d610ed7120>,

In [6]:
from solve import set_production_objective

set_production_objective(model, 'C_Spinosad')

目标设置为: C_Spinosad 的最大化生产

In [8]:
solution = model.optimize()
print("\n优化结果:")
print(f"目标值: {solution.objective_value:.6f}")
print(f"求解状态: {solution.status}")

# 了解Spinosad的输入输出行为
print("\nSpinosad生产情况:")
print(model.metabolites.C_Spinosad_c.summary())
print(model.metabolites.C_Spinosad_e.summary())

# 了解主要的能量(C00002<->atp)生产和消耗反应
print(model.metabolites.C00002_c.summary())

# 输出主要通量
print("\n主要代谢物通量:")
for ex in model.exchanges:
    if abs(solution.fluxes[ex.id]) > 1e-6:
        print(f"{ex.name}: {solution.fluxes[ex.id]:.6f}")

优化结果:
目标值: 21.947874
求解状态: optimal

Spinosad生产情况:
C_Spinosad_c
============
Formula:

Producing Reactions
-------------------
Percent  Flux   Reaction                                                                      Definition
100.00% 21.95 R_Assemble 3.0 C00019_c + C02199_c + C18034_c + C_AGL_c --> C00015_c + 3.0 C00021_c + C...

Consuming Reactions
-------------------
Percent   Flux   Reaction                    Definition
100.00% -21.95 R_Spinosad C_Spinosad_c --> C_Spinosad_e
C_Spinosad_e
============
Formula:

Producing Reactions
-------------------
Percent  Flux   Reaction                    Definition
100.00% 21.95 R_Spinosad C_Spinosad_c --> C_Spinosad_e

Consuming Reactions
-------------------
Percent   Flux        Reaction        Definition
100.00% -21.95 EX_C_Spinosad_e C_Spinosad_e <=>
C00002_c
========
Formula: C10H16N5O13P3

Producing Reactions
-------------------
Percent  Flux Reaction                                                                   Definition
 15.43% 879.3   R00200                                  C00008_c + C00074_c <=> C00002_c + C00022_c
 17.55%  1000   R00344            C00002_c + C00022_c + C00288_c <=> C00008_c + C00009_c + C00036_c
 15.43% 879.3   R01512                                  C00008_c + C00236_c <=> C00002_c + C00197_c
 17.55%  1000   R01737                                  C00002_c + C00257_c <=> C00008_c + C00345_c
 17.55%  1000   R06515 C00002_c + C00010_c + C11405_c <=> C00001_c + C00013_c + C00020_c + C11407_c
 16.49% 939.6    R_ATP       C00007_c + C00008_c + C00009_c + 4.0 C_H_e --> 3.0 C00001_c + C00002_c

Consuming Reactions
-------------------
Percent   Flux  Reaction                                                                      Definition
  1.32% -75.45    R00127                                            C00002_c + C00020_c <=> 2.0 C00008_c
  4.24% -241.4    R00130                                     C00002_c + C00882_c --> C00008_c + C00010_c
  0.39% -21.95    R00156                                     C00002_c + C00015_c <=> C00008_c + C00075_c
  1.93% -109.7    R00177               C00001_c + C00002_c + C00073_c --> C00009_c + C00013_c + C00019_c
  6.16% -351.2    R00185                                     C00002_c + C00212_c <=> C00008_c + C00020_c
  9.16% -521.9    R00299                                     C00002_c + C00031_c <=> C00008_c + C00092_c
  4.24% -241.4    R00509                                     C00002_c + C00224_c --> C00008_c + C00053_c
  4.24% -241.4    R00529                                     C00002_c + C00059_c --> C00013_c + C00224_c
  9.16% -521.9    R01092                                     C00002_c + C00124_c --> C00008_c + C00446_c
  0.77%  -43.9    R01353                                     C00002_c + C00163_c --> C00008_c + C02876_c
 15.43% -879.3    R01541                                     C00002_c + C00204_c --> C00008_c + C04442_c
  0.39% -21.95    R02093                                     C00008_c + C00459_c <=> C00002_c + C00363_c
  4.24% -241.4    R02473               C00002_c + C00099_c + C00522_c --> C00013_c + C00020_c + C00864_c
  4.24% -241.4    R03018                                     C00002_c + C00864_c --> C00008_c + C03492_c
  4.24% -241.4    R03035                                     C00002_c + C01134_c --> C00013_c + C00882_c
  4.24% -241.4    R04230               C00002_c + C00097_c + C03492_c --> C00013_c + C00020_c + C04352_c
 17.55%  -1000    R06396    C00002_c + C00010_c + C11405_c <=> C00001_c + C00008_c + C00009_c + C11407_c
  3.85% -219.5     R_AGL 4.0 C00001_c + 10.0 C00002_c + 11.0 C00005_c + 9.0 C00024_c + 11.0 C00080_c ...
  4.24% -241.4 R_Sulfate                          C00002_c + C00059_e --> C00008_c + C00009_c + C00059_c

主要代谢物通量:
Sulfate_e exchange: -241.426612
Spinosad_e exchange: 21.947874
Oxygen_e exchange: -939.643347
CO2_e exchange: 1000.000000
Formate_e exchange: 465.020576
Acetaldehyde_e exchange: -1000.000000
Formylanthranilate_e exchange: -241.426612
Guanine_e exchange: -829.903978
Hypoxanthine_e exchange: -1000.000000
Xanthine_e exchange: 1000.000000
Acetate_e exchange: -57.956104
Adenosine_e exchange: -241.426612
2-Oxoglutarate_e exchange: 461.591221
L-Aspartate_e exchange: -802.469136
Citrate_e exchange: -439.300412
D-Alanine_e exchange: 1000.000000
Deoxyguanosine_e exchange: 829.903978
Deoxyuridine_e exchange: -829.903978
Ethanol_e exchange: 1000.000000
4-Aminobutanoate_e exchange: 0.342936
D-Gluconic acid_e exchange: 1000.000000
2-Dehydro-3-deoxy-D-gluconate_e exchange: -879.286694
(S)-Malate_e exchange: 1000.000000
Melibiose_e exchange: -521.947874
Orthophosphate_e exchange: -724.279835
L-Proline_e exchange: -461.591221
Propanoate_e exchange: -43.895748
Pyruvate_e exchange: 1000.000000
L-Serine_e exchange: -816.186557
Succinate_e exchange: -1000.000000
L-Threonine_e exchange: 575.102881
Uracil_e exchange: 829.903978
H+_e exchange: 1000.000000
HCO3-_e exchange: 1000.000000
H_e exchange: -1000.000000

In [9]:
"""
BRENDA: TURNOVER NUMBER [1/s] 	SUBSTRATE
Sabio-RK:

https://cobrapy.readthedocs.io/en/latest/media.html:
fluxes have the unit mmol / [gDW h] (concentration per gram dry weight of cells and hour)

1kDa表示相对分子质量为1000的分子
酶的分子量为 50kDa = 50000g/mol(典型值)
假设总酶量占细胞干重的 40% (即 0.4g酶/gDW)。
总酶池约束为 0.008 mmol酶/gDW
"""

for reaction in model.reactions:
    # 每个反应对应一个酶
    # ub设置为总酶池约束
    enzyme_var = model.problem.Variable(f"Enzyme_{reaction.id}", lb=0, ub=8)
    model.add_cons_vars(enzyme_var)

    # 中位数约0.5（单位：1/s）
    kcat = 1800 # (单位：1/h)
    constraint_max = model.problem.Constraint(
        reaction.flux_expression - kcat * enzyme_var,
        ub=0,  # v_i - kcat*E_i ≤ 0 → v_i ≤ kcat*E_i
        name=f"enzyme_constraint_{reaction.id}_max"
    )
    constraint_min = model.problem.Constraint(
        reaction.flux_expression + kcat * enzyme_var,
        lb=0,  # v_i + kcat*E_i ≥ 0 → v_i ≥ -kcat*E_i
        name=f"enzyme_constraint_{reaction.id}_min"
    )
    model.add_cons_vars([constraint_max, constraint_min])

total_protein_content = 8  # 单位：0.008mmol/gDW（假设值）× 1000 = 8mmol/gDW (弥补求解器精度不足)
enzyme_vars = [ var for var in model.variables if var.name.startswith("Enzyme_")]

total_enzyme_expr = sum(enzyme_vars)
total_enzyme_constraint = model.problem.Constraint(
    total_enzyme_expr,
    lb=0,
    ub=total_protein_content,
    name="total_enzyme_constraint"
)
model.add_cons_vars(total_enzyme_constraint)

solution = model.optimize()
print(solution.fluxes)
print(model.summary())

R00004         0.000000e+00
R00005         0.000000e+00
R00006         0.000000e+00
R00009         6.332872e-16
R00013         0.000000e+00
                   ...
EX_C00105_e    0.000000e+00
EX_C00183_e   -7.008850e+01
EX_C00080_e   -1.529204e+02
EX_C00288_e    5.989381e+02
EX_C_H_e       0.000000e+00
Name: fluxes, Length: 1573, dtype: float64
Objective
=========
1.0 EX_C_Spinosad_e = 6.3716814159292

Uptake
------
Metabolite    Reaction  Flux  C-Number C-Flux
  C00007_e EX_C00007_e 184.8         0  0.00%
  C00009_e EX_C00009_e 210.3         0  0.00%
  C00042_e EX_C00042_e 369.6         4 26.73%
  C00049_e EX_C00049_e 70.09         4  5.07%
  C00059_e EX_C00059_e 70.09         0  0.00%
  C00065_e EX_C00065_e 101.9         3  5.53%
  C00067_e EX_C00067_e 70.09         1  1.27%
  C00080_e EX_C00080_e 152.9         0  0.00%
  C00084_e EX_C00084_e   669         2 24.19%
  C00122_e EX_C00122_e   223         4 16.13%
  C00163_e EX_C00163_e 12.74         3  0.69%
  C00183_e EX_C00183_e 70.09         5  6.34%
  C00212_e EX_C00212_e 70.09        10 12.67%
  C05402_e EX_C05402_e 6.372        12  1.38%

Secretion
---------
  Metabolite        Reaction   Flux  C-Number C-Flux
    C00022_e     EX_C00022_e   -669         3 52.85%
    C00033_e     EX_C00033_e -121.1         2  6.38%
    C00133_e     EX_C00133_e -70.09         3  5.54%
    C00188_e     EX_C00188_e -25.49         4  2.68%
    C00288_e     EX_C00288_e -598.9         1 15.77%
    C00469_e     EX_C00469_e -318.6         2 16.78%
C_Spinosad_e EX_C_Spinosad_e -6.372         0  0.00%

In [11]:
import pandas as pd
from cobra.flux_analysis import (single_gene_deletion, single_reaction_deletion)

single_reaction_deletion_results = single_reaction_deletion(model)
single_reaction_deletion_results.to_csv('../data/single_reaction_deletion_results.csv')
print(f"结果已保存到: '../data/single_reaction_deletion_results.csv'")

结果已保存到: '../data/single_reaction_deletion_results.csv'

In [14]:
def find_essential_single_reaction(model, production_threshold=0.4):
    """
    Find essential single reaction
    param production_threshold: The minimum production change threshold to consider a reaction essential.
    return: A list of essential reactions.
    """
    essential_reactions = []
    objective_value = model.optimize().objective_value
    single_reaction_deletion_results = pd.read_csv('../data/single_reaction_deletion_results.csv')
    for _, row in single_reaction_deletion_results.iterrows():
        if row['status'] != 'optimal':
            continue
        if abs((row['growth'] - objective_value) / objective_value) >= production_threshold:
            essential_reactions.append(row['ids'])
    return essential_reactions

essential_reactions = find_essential_single_reaction(model)
print(f"Essential reactions: {essential_reactions}")

Essential reactions: ["{'R03018'}", "{'R00293'}", "{'R00130'}", "{'R08931'}", "{'R08930'}", "{'R00289'}", "{'R02021'}", "{'R06430'}", "{'R00946'}", "{'R00529'}", "{'R_Propanoate'}", "{'R08705'}", "{'EX_C_Spinosad_e'}", "{'R00177'}", "{'R02473'}", "{'R08932'}", "{'R00489'}", "{'EX_C00059_e'}", "{'R00192'}", "{'R02472'}", "{'R00188'}", "{'EX_C00163_e'}", "{'R06428'}", "{'R08704'}", "{'R02328'}", "{'R_Spinosad'}", "{'R06513'}", "{'R_Sulfate'}", "{'R03269'}", "{'R_Assemble'}", "{'R_AGL'}", "{'R02093'}", "{'R00858'}", "{'R03035'}", "{'R00509'}"]

In [ ]:
import pandas as pd
from cobra.flux_analysis import (single_gene_deletion, single_reaction_deletion)

# 创建一个空的 DataFrame 用于存储反应ID和优化结果
knockout_single_reaction_result = []
knockout_single_gene_results = []

def knock_out_single_reaction(model, reaction_id):
    """
    Knock out single reaction
    Able to specify the reaction ID
    """
    with model:
        model.reactions.get_by_id(reaction_id).knock_out()
        solution = model.optimize()
        knockout_single_reaction_result.append({'Reaction ID': reaction_id, 'Objective Value': solution.objective_value})


def find_essential_single_reaction(model, production_threshold=0.01):
    """
    Find essential single reaction
    param production_threshold: The minimum production change threshold to consider a reaction essential.
    return: A list of essential reactions.
    """
    essential_reactions = []
    objective_value = model.optimize().objective_value
    single_reaction_deletion_results = pd.read_csv('../data/single_reaction_deletion_results.csv')
    for _, row in single_reaction_deletion_results.iterrows():
        if row['status'] != 'optimal':
            continue
        if abs((row['growth'] - objective_value) / objective_value) >= production_threshold:
            essential_reactions.append(row['ids'])
    return essential_reactions

for reaction in model.reactions:
    knock_out_single_reaction(model, reaction.id)

# 将结果转换为 DataFrame
knockout_single_reaction_df_result = pd.DataFrame(knockout_single_reaction_result)
# 将 DataFrame 存储为 CSV 文件
knockout_single_reaction_df_result.to_csv('../data/knockout_single_reaction_result.csv', index=False)
print(f"结果已保存到: '../data/knockout_single_reaction_result.csv'")

knock_out_single_genes_and_reactions(model)

essential_reactions = find_essential_single_reaction(model)
print(f"Essential reactions: {essential_reactions}")
essential_genes = find_essential_single_gene(model)
print(f"Essential genes: {essential_genes}")

In [13]:
import requests
# 获取KO编号K00001的信息
ko_response = requests.get("http://rest.kegg.jp/get/ko:K00033/json")
print(ko_response.content)
# ec_numbers = [line.split()[1] for line in ko_response.text.split('\n') if line.startswith('EC:')]
# print(ec_numbers)
# # 通过EC编号获取反应
# for ec in ec_numbers:
#     rn_response = requests.get(f"http://rest.kegg.jp/link/rn/{ec}")
#     print(rn_response.text)

b''

----------------------------------------------------------------------------------------------------

In [25]:
import pandas as pd
chr_kegg = pd.read_csv('../data/NRRL_1/7_Annotation/chr.kegg.csv')

In [26]:
chr_kegg

,orf_name,Class D,Class C,Class B,Class A
0,chr_1,K02313 dnaA; chromosomal replication initiato...,02020 Two-component system,Signal transduction,Environmental Information Processing
1,chr_1,K02313 dnaA; chromosomal replication initiato...,04112 Cell cycle - Caulobacter,Cell growth and death,Cellular Processes
2,chr_1,K02313 dnaA; chromosomal replication initiato...,03032 DNA replication proteins,Protein families: genetic information processing,Brite Hierarchies
3,chr_1,K02313 dnaA; chromosomal replication initiato...,03036 Chromosome and associated proteins,Protein families: genetic information processing,Brite Hierarchies
4,chr_2,K02338 dnaN; DNA polymerase III subunit beta,03430 Mismatch repair,Replication and repair,Genetic Information Processing
...,...,...,...,...,...
5007,chr_8224,"K03217 yidC, spoIIIJ, OXA1, ccfA; YidC/Oxa1 f...",03070 Bacterial secretion system,Membrane transport,Environmental Information Processing
5008,chr_8224,"K03217 yidC, spoIIIJ, OXA1, ccfA; YidC/Oxa1 f...",02024 Quorum sensing,Cellular community - prokaryotes,Cellular Processes
5009,chr_8224,"K03217 yidC, spoIIIJ, OXA1, ccfA; YidC/Oxa1 f...",03029 Mitochondrial biogenesis,Protein families: genetic information processing,Brite Hierarchies
5010,chr_8224,"K03217 yidC, spoIIIJ, OXA1, ccfA; YidC/Oxa1 f...",02044 Secretion system,Protein families: signaling and cellular proce...,Brite Hierarchies
5011,chr_8225,K08998 K08998; uncharacterized protein,99997 Function unknown,Poorly characterized,Not Included in Pathway or Brite

In [28]:
# 筛选 class A 列为 'metabolism' 的行
chr_kegg_metabolism = chr_kegg[chr_kegg['Class A'] == 'Metabolism']
# 新增 KO number 列（从 class D 列提取）
chr_kegg_metabolism['KO number'] = chr_kegg_metabolism ['Class D'].str.split(n=1).str[0]
chr_kegg_metabolism

C:\Users\Victor\AppData\Local\Temp\ipykernel_40956\3156565885.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chr_kegg_metabolism['KO number'] = chr_kegg_metabolism ['Class D'].str.split(n=1).str[0]

,orf_name,Class D,Class C,Class B,Class A,KO number
9,chr_3,"K00033 PGD, gnd, gntZ; 6-phosphogluconate deh...",00480 Glutathione metabolism,Metabolism of other amino acids,Metabolism,K00033
10,chr_3,"K00033 PGD, gnd, gntZ; 6-phosphogluconate deh...",00030 Pentose phosphate pathway,Carbohydrate metabolism,Metabolism,K00033
22,chr_27,K01658 trpG; anthranilate synthase component II,"00400 Phenylalanine, tyrosine and tryptophan b...",Amino acid metabolism,Metabolism,K01658
23,chr_27,K01658 trpG; anthranilate synthase component II,00405 Phenazine biosynthesis,Biosynthesis of other secondary metabolites,Metabolism,K01658
28,chr_30,K05364 pbpA; penicillin-binding protein A,00550 Peptidoglycan biosynthesis,Glycan biosynthesis and metabolism,Metabolism,K05364
...,...,...,...,...,...,...
4970,chr_8198,"K00232 E1.3.3.6, ACOX1, ACOX3; acyl-CoA oxidase",01040 Biosynthesis of unsaturated fatty acids,Lipid metabolism,Metabolism,K00232
4986,chr_8214,"K00384 trxB, TRR; thioredoxin reductase (NADPH)",00450 Selenocompound metabolism,Metabolism of other amino acids,Metabolism,K00384
4993,chr_8218,K05825 LYSN; 2-aminoadipate transaminase,00300 Lysine biosynthesis,Amino acid metabolism,Metabolism,K05825
4994,chr_8219,K01921 ddl; D-alanine-D-alanine ligase,00473 D-Alanine metabolism,Metabolism of other amino acids,Metabolism,K01921
4995,chr_8219,K01921 ddl; D-alanine-D-alanine ligase,00550 Peptidoglycan biosynthesis,Glycan biosynthesis and metabolism,Metabolism,K01921

In [33]:
chr_kegg_metabolism = chr_kegg_metabolism[['orf_name', 'KO number']]
# 去重
chr_kegg_metabolism = chr_kegg_metabolism.drop_duplicates(subset=["KO number"], keep="first")
# 写入文件（不保留索引）
chr_kegg_metabolism.to_csv('../data/NRRL_1/7_Annotation/chr.kegg.metabolism.csv', index=False)

---------------------------------------------------------------------------------------------------

In [47]:
from bioservices import KEGG

k = KEGG()
data = k.get("K00033")
dict_data = k.parse(data)
print(dict_data)

{'ENTRY': 'K00033                      KO', 'SYMBOL': 'PGD, gnd, gntZ', 'NAME': ['6-phosphogluconate dehydrogenase [EC:1.1.1.44 1.1.1.343]'], 'PATHWAY': {'map00030': 'Pentose phosphate pathway', 'map00480': 'Glutathione metabolism', 'map01100': 'Metabolic pathways', 'map01110': 'Biosynthesis of secondary metabolites', 'map01120': 'Microbial metabolism in diverse environments', 'map01200': 'Carbon metabolism'}, 'MODULE': {'M00004': 'Pentose phosphate pathway (Pentose phosphate cycle)', 'M00006': 'Pentose phosphate pathway, oxidative phase, glucose 6P => ribulose 5P'}, 'REACTION': ['R01528', '6-phospho-D-gluconate:NADP+', '2-oxidoreductase', '(decarboxylating)', 'R10221', '6-phospho-D-gluconate:NAD+', '2-oxidoreductase', '(decarboxylating)'], 'BRITE': 'KEGG Orthology (KO) [BR:ko00001]\n             09100 Metabolism\n              09101 Carbohydrate metabolism\n               00030 Pentose phosphate pathway\n                K00033  PGD, gnd, gntZ; 6-phosphogluconate dehydrogenase\n              09106 Metabolism of other amino acids\n               00480 Glutathione metabolism\n                K00033  PGD, gnd, gntZ; 6-phosphogluconate dehydrogenase\n            Enzymes [BR:ko01000]\n             1. Oxidoreductases\n              1.1  Acting on the CH-OH group of donors\n               1.1.1  With NAD+ or NADP+ as acceptor\n                1.1.1.44  phosphogluconate dehydrogenase (NADP+-dependent, decarboxylating)\n                 K00033  PGD, gnd, gntZ; 6-phosphogluconate dehydrogenase\n                1.1.1.343  phosphogluconate dehydrogenase (NAD+-dependent, decarboxylating)\n                 K00033  PGD, gnd, gntZ; 6-phosphogluconate dehydrogenase', 'DBLINKS': {'COG': 'COG0362 COG1023', 'GO': '0004616'}, 'GENES': {'HSA': '5226(PGD)', 'PTR': '100612990(PGD) 459464', 'PPS': '100985461(KIF1B) 100994285', 'GGO': '101151718(PGD)', 'PON': '100433341(PGD)', 'PPYG': '129008157(PGD)', 'NLE': '100598383(PGD)', 'HMH': '116812900(PGD)', 'SSYN': '129472337(PGD)', 'MCC': '107000661(PGD)', 'MCF': '101866917(PGD)', 'MTHB': '126953092', 'MNI': '105473134(PGD)', 'CSAB': '103225982(PGD)', 'CATY': '105580884(PGD)', 'PANU': '101006798(PGD)', 'TGE': '112632737(PGD)', 'MLEU': '105551418(PGD)', 'RRO': '104663043(PGD)', 'RBB': '108539343', 'TFN': '117093337(PGD)', 'PTEH': '113219516(PGD)', 'CANG': '105507340(PGD) 105516974', 'CJC': '100401515(PGD)', 'SBQ': '101050003(PGD)', 'CIMI': '108286161(PGD) 108295743', 'ANAN': '105720223 105731739(PGD)', 'CSYR': '103267351(PGD)', 'MMUR': '105886057(PGD)', 'LCAT': '123634491(PGD)', 'PCOQ': '105824889(PGD)', 'OGA': '100947431 100955033(PGD)', 'MMU': '110208(Pgd)', 'MCAL': '110293709(Pgd)', 'MPAH': '110322749(Pgd)', 'RNO': '100360180(Pgd)', 'MCOC': '116097028(Pgd)', 'ANU': '117709179(Pgd)', 'ASYL': '127681674(Pgd)', 'MUN': '110545918 110548137(Pgd)', 'CGE': '100765199(Pgd)', 'MAUA': '101830889(Pgd)', 'PROB': '127213549(Pgd)', 'PLEU': '114692439 114709637(Pgd)', 'MORG': '121441741 121447944', 'MFOT': '126508232', 'AAMP': '119816225(Pgd)', 'NGI': '103733013(Pgd)', 'HGL': '101701691(Pgd)', 'CPOC': '101788565(Pgd)', 'CCAN': '109700794(Pgd)', 'DORD': '106000063(Pgd)', 'DSP': '122121456(Pgd)', 'PLOP': '125354559(Pgd)', 'NCAR': '124978008', 'MMMA': '107155513(Pgd)', 'ITI': '101958319(Pgd)', 'OCU': '100353441', 'OPI': '101532564(PGD)', 'TUP': '102492371(PGD)', 'GVR': '103587368(PGD)', 'CFA': '478236(PGD)', 'CLUD': '112662585(PGD)', 'VVP': '112929731(PGD)', 'VLG': '121497129(PGD)', 'NPO': '129513331(PGD)', 'AML': '100479518(PGD) 117800374', 'UMR': '121106407(PGD)', 'UAH': '113270522(PGD)', 'UAR': '123779087(PGD)', 'ELK': '111154630', 'LLV': '125096812', 'MPUF': '101680821(PGD)', 'MNP': '132001103(PGD)', 'MLK': '131809065(PGD)', 'NVS': '122899436(PGD)', 'ORO': '101385835(PGD)', 'EJU': '114213133(PGD)', 'ZCA': '113923523(PGD)', 'MLX': '118020019(PGD)', 'NSU': '110575123(PGD)', 'LWW': '102749800(PGD)', 'FCA': '101096246(PGD)', 'PYU': '121020885(PGD)', 'PCOO': '112868695(PGD)', 'PBG': '122482074(PGD)', 'PVIV': '125171943(PGD)', 'LRUF': '124514809', 'LGF': '123599802(PGD)', 'AJU': '106984920', 'PTG': '102953665(PGD)', 'PPAD': '109274092(PGD)', 'PUC': '125913133', 'PLEZ': '122228624(PGD)', 'HHV': '120233645(PGD)', 'BTA': '514939(PGD)', 'BOM': '102270573(PGD)', 'BIU': '109570632(PGD)', 'BBUB': '102412248(PGD)', 'BBIS': '104995855(PGD)', 'CHX': '102176986(PGD)', 'OAS': '443541(PGD)', 'CSUM': '138090504(PGD)', 'ODA': '120880197(PGD)', 'CCAD': '122451830(PGD)', 'MREE': '136168389(PGD)', 'OVR': '110135128(PGD)', 'MBEZ': '129551520(PGD)', 'SSC': '397546(PGD)', 'CFR': '102509152(PGD)', 'CBAI': '105070985(PGD)', 'CDK': '105107012(PGD)', 'VPC': '102527509(PGD)', 'BACU': '103009369(PGD)', 'BMUS': '118889740(PGD)', 'LVE': '103072604(PGD)', 'OOR': '101281588(PGD)', 'LALB': '132515245(PGD)', 'DLE': '111187279', 'PCAD': '102973864(PGD)', 'PSIU': '116748941(PGD)', 'NASI': '112402669(PGD)', 'ECB': '100146298(PGD)', 'EPZ': '103549069(PGD)', 'EAI': '106836687(PGD)', 'MYB': '102263834(PGD)', 'MYD': '102769523(PGD)', 'MMYO': '118677606(PGD)', 'MLF': '102428134(PGD)', 'MDT': '132231707(PGD)', 'MYUM': '139002855(PGD)', 'PKL': '118732050(PGD)', 'EFUS': '103295313(PGD)', 'MNA': '107538451(PGD)', 'DRO': '112299093(PGD)', 'SHON': '118986365(PGD)', 'AJM': '119064082(PGD)', 'PDIC': '114497818(PGD)', 'PHAS': '123832206(PGD)', 'MMF': '118626179(PGD) 118641112', 'PPAM': '129075666(PGD)', 'HAI': '109381236(PGD)', 'RFQ': '117027222(PGD)', 'PALE': '102882403(PGD)', 'PGIG': '120585832', 'PVP': '105294431(PGD)', 'RAY': '107513099(PGD)', 'MJV': '108400730(PGD)', 'TOD': '119237289(PGD)', 'SARA': '101539754 101549093(PGD)', 'SFUM': '130020365(PGD)', 'SETR': '126011532(PGD)', 'LAV': '100663705(PGD)', 'TMU': '101340924', 'ETF': '101657994', 'DNM': '101431494(PGD)', 'MDO': '100618839(PGD)', 'GAS': '123243089(PGD)', 'SHR': '100920891(PGD)', 'AFZ': '127555890', 'PCW': '110199343(PGD)', 'TVP': '118840422(PGD)', 'PBRV': '138154523(PGD)', 'OAA': '100078793(PGD)', 'TACU': '119928355(PGD)', 'GGA': '419450(PGD)', 'PCOC': '116242539(PGD)', 'MGP': '104914120(PGD)', 'CJO': '107323383(PGD)', 'TPAI': '128084841(PGD)', 'LMUT': '125703458(PGD)', 'NMEL': '110386969(PGD)', 'APLA': '101801278(PGD)', 'ACYG': '106044311(PGD)', 'CATA': '118253269(PGD)', 'AFUL': '116497690(PGD)', 'TGU': '100534626(PGD)', 'LSR': '110470299(PGD)', 'SCAN': '103820774(PGD)', 'PMOA': '120511080(PGD)', 'OTC': '121343983(PGD)', 'PRUF': '121349644(PGD)', 'ATRC': '139600591(PGD)', 'GFR': '102032080(PGD)', 'FAB': '101816088(PGD)', 'OMA': '130261708(PGD)', 'PHI': '102105577(PGD)', 'PMAJ': '107213662(PGD)', 'CCAE': '111938687(PGD)', 'CCW': '104693345(PGD)', 'CBRC': '103622237(PGD)', 'ACOE': '138121539(PGD)', 'ETL': '114056887(PGD)', 'ZAB': '102061857(PGD)', 'ZLE': '135456802(PGD)', 'ACHL': '103808104(PGD)', 'SVG': '106862704(PGD)', 'MMEA': '130579287(PGD)', 'HRT': '120762300(PGD)', 'SATI': '136370872(PGD)', 'CCIC': '134052934(PGD)', 'FPG': '101920426(PGD)', 'FCH': '102056312(PGD)', 'CCRI': '104155255(PGD)', 'NNT': '104399750(PGD)', 'SHAB': '115617391(PGD)', 'ACUN': '113487730(PGD)', 'TALA': '104355612(PGD)', 'ACHC': '115342705(PGD)', 'HALD': '104311123(PGD)', 'HLE': '104837906(PGD)', 'AGEN': '126046486', 'HHAR': '128143931(PGD)', 'GCL': '127024721', 'CSTI': '104550323(PGD)', 'LDI': '104347971(PGD)', 'MNB': '103767881(PGD)', 'DPUB': '104305853(PGD)', 'PPUS': '135190674(PGD)', 'AVIT': '104270392(PGD)', 'BRHI': '104488132(PGD)', 'EGZ': '104133071(PGD)', 'NNI': '104008987(PGD)', 'PCRI': '104024696(PGD)', 'PCAO': '104049329(PGD)', 'AFOR': '103907459(PGD)', 'FGA': '104070052(PGD)', 'GSTE': '104251095(PGD)', 'CBOY': '140661747(PGD)', 'CLV': '102093534(PGD)', 'MUI': '104539817(PGD)', 'PGUU': '104463821(PGD)', 'PLET': '104614374(PGD)', 'EHS': '104503443(PGD)', 'CMAC': '104473463(PGD)', 'CUCA': '104060542(PGD)', 'TEO': '104380474(PGD)', 'BREG': '104629787(PGD)', 'OHA': '104332792(PGD)', 'ACAR': '104518336(PGD)', 'CPEA': '104395448(PGD)', 'CVF': '104290460(PGD)', 'RTD': '128918253(PGD)', 'CRID': '134524301(PGD)', 'AAM': '106499068(PGD)', 'AROW': '112970034(PGD)', 'NPD': '112959592(PGD)', 'TGT': '104573811(PGD)', 'DNE': '112980572(PGD)', 'SCAM': '104141877(PGD)', 'ASN': '102387227(PGD)', 'AMJ': '102568263(PGD)', 'CPOO': '109314466(PGD)', 'GGN': '109293686(PGD)', 'PSS': '102449943(PGD)', 'CMY': '102930318(PGD)', 'CCAY': '125624398(PGD)', 'DCC': '119844986(PGD)', 'CPIC': '101952747(PGD)', 'TST': '117867960(PGD)', 'CABI': '116821969(PGD)', 'MRV': '120387804(PGD)', 'ASAO': '132764809(PGD)', 'PVT': '110073240(PGD)', 'SUND': '121936802(PGD)', 'PBI': '103056523(PGD)', 'PMUR': '107292356(PGD)', 'CTIG': '120319153(PGD)', 'TSR': '106553110(PGD)', 'PGUT': '117678116(PGD)', 'APRI': '131187109(PGD)', 'PTEX': '113446246(PGD)', 'NSS': '113424638(PGD)', 'VKO': '123030981(PGD)', 'PMUA': '114602461(PGD)', 'PRAF': '128419787(PGD)', 'ZVI': '118086565(PGD)', 'HCG': '128338394(PGD)', 'GJA': '107124363(PGD)', 'STOW': '125445588(PGD)', 'EMC': '129344481(PGD)', 'XLA': '398848(pgd.L)', 'XTR': '100491794(pgd)', 'NPR': '108804932(PGD)', 'RTEM': '120915698(PGD)', 'BBUF': '120999718(PGD)', 'BGAR': '122928815(PGD)', 'PWL': '138301095(PGD)', 'GSH': '117349370(PGD)', 'DRE': '406762(pgd)', 'SRX': '107708839 107716232', 'SANH': '107681986 107695776', 'SGH': '107570752 107586524', 'CCAR': '109060966 109113850', 'CAUA': '113041478 113065469 113065536', 'CGIB': '127945112 128011963', 'PTET': '122329074(pgd)', 'LROH': '127155137(pgd)', 'OMC': '131531750(pgd)', 'PPRM': '120463712(pgd)', 'RKG': '130074106(pgd)', 'MAMB': '125260087(pgd)', 'CIDE': '127504820', 'CERY': '137009205(pgd)', 'MASI': '127419161 127420135', 'TROS': '130545531(pgd)', 'TDW': '130409637(pgd)', 'MANU': '129430761(pgd)', 'PDAB': '135775410(pgd)', 'IPU': '108276249', 'IFU': '128619721(pgd)', 'PHYP': '113530486(pgd)', 'TFD': '113658243(pgd)', 'TVC': '132861958(pgd)', 'CGAR': '128510345(pgd)', 'TRN': '134333298(pgd)', 'AMEX': '103026797(pgd)', 'CMAO': '118822287(pgd)', 'EEE': '113581279(pgd)', 'CHAR': '122130839(pgd)', 'SPIL': '134087893(pgd)', 'TRU': '101072234(pgd)', 'TFS': '130529503(pgd)', 'TNG': 'GSTEN00028241G001', 'LCO': '104919442(pgd)', 'NCC': '104954116(pgd)', 'TBEN': '117494394(pgd)', 'CGOB': '115010734(pgd)', 'PGEO': '117449164(pgd)', 'GACU': '117541836(pgd)', 'EMAC': '134869329(pgd)', 'ELY': '117258190(pgd)', 'EFO': '125892348(pgd)', 'PLEP': '121946511(pgd)', 'SLUC': '116040898(pgd)', 'ECRA': '117948180(pgd)', 'ESP': '116674440 116692918(pgd)', 'PFLV': '114558747(pgd)', 'GAT': '120829814(pgd)', 'PPUG': '119222830(pgd)', 'AFB': '129099841(pgd)', 'CLUM': '117733335(pgd)', 'PSWI': '130199785(pgd)', 'CANA': '137800342(pgd)', 'CVE': '137889488(pgd)', 'MSAM': '119919333(pgd)', 'SCHU': '122883432(pgd)', 'CUD': '121517295(pgd)', 'SPUL': '138590192(pgd)', 'LMIX': '132989249(pgd)', 'ALAT': '119023607(pgd)', 'ASTR': '137613838(pgd)', 'MZE': '101465665(pgd)', 'ONL': '100705056(pgd)', 'OAU': '116309734(pgd)', 'OLA': '101173937(pgd)', 'OML': '112158831(pgd)', 'CSAI': '133457300(pgd)', 'XMA': '102227359(pgd)', 'XCO': '114143207(pgd)', 'XHE': '116725913(pgd)', 'PRET': '103467221(pgd)', 'PFOR': '103138912(pgd)', 'PLAI': '106942696(pgd)', 'PMEI': '106931271(pgd)', 'GAF': '122834525(pgd)', 'PPRL': '129372318(pgd)', 'CVG': '107086873(pgd)', 'CTUL': '119797096(pgd)', 'GMU': '124867947(pgd)', 'NFU': '107390748(pgd)', 'KMR': '108236805(pgd)', 'ALIM': '106534251(pgd)', 'NWH': '119417659(pgd)', 'AOCE': '111573226(pgd)', 'EJA': '138193217(pgd)', 'BFRE': '138615401(pgd)', 'MCEP': '125004600(pgd)', 'CSEM': '103385034(pgd)', 'POV': '109630730(pgd)', 'SSEN': '122776823(pgd)', 'SSOE': '131468391(pgd)', 'HHIP': '117764883(pgd)', 'HSP': '118111065(pgd)', 'PPLT': '128442544(pgd)', 'SMAU': '118316350(pgd)', 'LCF': '108876386', 'SDU': '111219008(pgd)', 'SLAL': '111670644(pgd)', 'XGL': '120803684(pgd)', 'HCQ': '109526611(pgd)', 'SSCV': '125988613(pgd)', 'SBIA': '133508257(pgd)', 'PEE': '133404918(pgd)', 'PTAO': '133482178(pgd)', 'BPEC': '110164533(pgd)', 'ENY': '140363540(pgd)', 'MALB': '109970334(pgd)', 'BSPL': '114858185(pgd)', 'SJO': '128357420(pgd)', 'SSCO': '133987871(pgd)', 'GMH': '115545422(pgd)', 'SASA': '100195559(pgd)', 'STRU': '115165919(pgd)', 'OTW': '112232610(pgd)', 'OMY': '110532327(pgd)', 'OGO': '124031975(pgd)', 'ONE': '115132200(pgd)', 'OKI': '109908034(pgd)', 'OKE': '118360992(pgd)', 'OMM': '135504367(pgd)', 'OCLA': '139416536', 'SALP': '111966486(pgd)', 'SNH': '120059313(pgd)', 'CCLU': '121538385(pgd)', 'ELS': '105022965(pgd)', 'OEP': '134019400(pgd)', 'SFM': '108923266(pgd)', 'PKI': '111834417(pgd)', 'AANG': '118208681(pgd)', 'AROT': '135235374(pgd)', 'CCOG': '133138486(pgd)', 'LOC': '102694256(pgd)', 'PSPA': '121328586 121328634', 'ARUT': '117425534 117432110', 'PSEX': '120530884(pgd)', 'LCM': '102363776(PGD)', 'CMK': '103184241(pgd)', 'RTP': '109936800(pgd)', 'CPLA': '122540442(pgd)', 'HOC': '132833810(pgd)', 'LERI': '129711741(pgd)', 'LRJ': '133351201(PGD)', 'BFO': '118430769', 'BBEL': '109484108 109484210', 'CIN': '100187169', 'SCLV': '120328908', 'SPU': '575941', 'LPIC': '129275840', 'AJJ': '139975538', 'APLC': '110989840', 'ARUN': '117302145', 'AAMU': '139950608', 'AFIL': '140157212', 'AJC': '117123594', 'SKO': '100370419', 'PFLL': '139137833', 'DME': 'Dmel_CG3724(Pgd)', 'DER': '6555625', 'DSE': '6616093', 'DSI': 'Dsimw501_GD16588(Dsim_Pgd)', 'DYA': 'Dyak_GE16239(Dyak_Pgd)', 'DAN': '6504145', 'DSR': '110180201', 'DPO': '4814420', 'DPE': '6596889', 'DMN': '108152379', 'DWI': '6648674', 'DGR': '6566362', 'DMO': 'Dmoj_GI11069', 'DAZ': '108618705', 'DNV': '108657447', 'DHE': '111593506', 'DVI': '6633266(Pgd)', 'CCAT': '101451876', 'BOD': '106626188', 'BDR': '105224335', 'RZE': '108365523 108378910', 'AOQ': '129236838', 'ALUD': '128857124', 'TDA': '119668557', 'MDE': '101897293', 'SCAC': '106093134', 'LCQ': '111675160', 'LSQ': '119616421', 'CVJ': '135958873(Pgd)', 'GFS': '119634129', 'ECOE': '129945597', 'CLON': '129614952 129616613', 'HIS': '119646870', 'AGA': '1274031', 'ACOZ': '120947760', 'AARA': '120906537', 'AMER': '121587672', 'ASTE': '118503010', 'AMAP': '126557892', 'AFUN': '125761282', 'AMOU': '128310646', 'AMRS': '128710365', 'AALI': '118460650', 'ACOS': '131259400', 'AAG': '5567259', 'AALB': '109416303', 'ASUA': '134224223', 'CQU': 'CpipJ_CPIJ001316 CpipJ_CPIJ008427 CpipJ_CPIJ012165 CpipJ_CPIJ019262', 'CPII': '120413932', 'CBRI': '134831925', 'CNS': '116339869', 'BCOO': '119078074', 'LLL': '129793231', 'PPAP': '129803586', 'AME': '552712', 'ACER': '107998382', 'ALAB': '122720998', 'ADR': '102674517', 'AFLR': '100870801', 'BIM': '100747505', 'BBIF': '117210090', 'BVK': '117241845', 'BVAN': '117157005', 'BHUN': '126870840', 'BTER': '100645214', 'BAFF': '126920916', 'BPYO': '122573637', 'BPAS': '132916074', 'FVI': '122532631', 'CCAL': '108622158', 'OBB': '114872031', 'OLG': '117605679', 'MGEN': '117219786', 'NMEA': '116424815', 'CGIG': '122401801', 'SOC': '105204535', 'MPHA': '105835226', 'AEC': '105154495', 'ACEP': '105621088', 'PBAR': '105430779', 'VEM': '105563071', 'COBS': '139113348(Pgd)', 'TLN': '139816762(Pgd)', 'HST': '105185900', 'DQU': '106745806', 'CFO': '105256452', 'FEX': '115238706', 'PMEC': '138936026(Pgd)', 'LHU': '105668940(Pgd)', 'PGC': '109851761', 'OBO': '105275255', 'PCF': '106788842', 'PFUC': '122525220', 'VPS': '122627820', 'VCRB': '124422976', 'VVE': '124948180', 'NVI': '100120510', 'CSOL': '105360238', 'TPRE': '106657942', 'LHT': '122498014', 'LBD': '127282826', 'MDL': '103571233', 'CGLO': '123260624', 'FAS': '105263212', 'DAM': '107039946', 'AGIF': '122859242', 'CINS': '118074288', 'VCAN': '122418935', 'CCIN': '107270069', 'DSM': '124408533', 'NPT': '124218225(Pgd)', 'NFB': '124179431', 'NLO': '107224327', 'NVG': '124302115', 'AROA': '105691606', 'TCA': '660752', 'TMOL': '138131388(Pgd)', 'DPA': '109540777', 'ESIM': '136414983(Pgd)', 'EFOR': '136341805(Pgd)', 'SOY': '115885429', 'AGRG': '126740086', 'ATD': '109602520', 'CSET': '123312498', 'HAXR': '123679042', 'AGB': '108915884', 'LDC': '111503603', 'DVV': '126887140', 'NVL': '108562864', 'APLN': '108742171 108742178 112904623', 'PPYR': '116159812', 'OTU': '111428041', 'BMOR': '733113', 'BMAN': '114245171', 'MSEX': '115444850', 'DPL': 'KGM_203400', 'BANY': '112048148', 'MJU': '123880608', 'NIQ': '126780408', 'VCD': '124542971', 'MCIX': '123669043', 'PMAC': '106717054', 'PPOT': '106110253', 'PXU': '106126275', 'BPHI': '137921925(Pgd)', 'PRAP': '110996324 110999278', 'PBX': '123719013', 'PNAP': '125062244', 'ZCE': '119835909', 'CCRC': '123705083', 'LSIN': '126971395', 'AAGE': '121738549', 'HAW': '110382514', 'HZE': '124644773', 'SLIU': '111360573', 'OFU': '114354090', 'ONU': '135086853', 'ATRA': '106130553', 'GMW': '113516568', 'PXY': '105381591', 'PGW': '126380518', 'LGLY': '125241964', 'CSTB': '134754315', 'CFEL': '113366704', 'CCRN': '123305804', 'API': '100167791', 'DNX': '107164684', 'AGS': '114124401', 'RMD': '113550639', 'ACOO': '126838984', 'DVT': '126901833', 'BTAB': '109039608', 'DCI': '103510040', 'CLEC': '106670775', 'HHAL': '106684795(Pgd)', 'NLU': '111057817', 'HVI': '124359513', 'MQU': '128991858 128991877', 'FOC': '113218219', 'TPAL': '117643616', 'ZNE': '110830346', 'CSEC': '111873567', 'PAME': '138705263(Pgd)', 'SGRE': '126295000 126316920', 'BROR': '134541280', 'IEL': '124163641', 'HAMR': '139696614(Pgd)', 'FCD': '110846215', 'DPX': 'DAPPUDRAFT_240002 DAPPUDRAFT_300918 DAPPUDRAFT_328991', 'DMK': '116926361 116929382', 'DPZ': '124311144 124343438', 'AFRA': '136026357 136032183', 'PVM': '113803123(Pgd)', 'PJA': '122242748 122261972', 'PCHN': '125046774', 'PMOO': '119579003', 'HAME': '121862093', 'PCLA': '123746917(Pgd)', 'CQD': '128699074(Pgd)', 'PTRU': '123511383', 'ESN': '127008402', 'MNZ': '135214489', 'MRJ': '136854886(Pgd)', 'PORN': '139757260(Pgd)', 'HAZT': '108678210', 'EAF': '111704517', 'LSM': '121130566(Pgd)', 'TCF': '131885175', 'PPOI': '119114914', 'ISC': '8034678', 'DSV': '119446256', 'RMP': '119175604', 'VDE': '111244007', 'VJA': '111270586', 'TUT': '107361683', 'DPTE': '113788659 113794111 113794481', 'DFR': '124500549', 'CSCU': '111635625', 'CVS': '136987340(Pgd)', 'PTEP': '107453087', 'ABRU': '129987860', 'UDV': '129225577', 'SDM': '118193924', 'LPOL': '106459107', 'PMEO': '129600099', 'CEL': 'CELE_T25B9.9(T25B9.9)', 'CBR': 'CBG_17632', 'CRQ': 'GCK72_014890', 'NAI': 'NECAME_14992', 'BMY': 'BM_BM13964(Bm13964)', 'LOA': 'LOAG_08072', 'TSP': 'Tsp_07649', 'HRO': 'HELRODRAFT_100404 HELRODRAFT_187587', 'LGI': 'LOTGIDRAFT_150160', 'PVUL': '126826882', 'PCAN': '112556079', 'LSAX': '138978410', 'BGT': '106056049', 'GAE': '121389878', 'HRF': '124139126', 'HRJ': '124261223', 'HASI': '137267898', 'HCRA': '139471569', 'CRG': '105345317', 'CANU': '128190005', 'CVN': '111137005', 'OED': '125663703', 'MYI': '110460402', 'PMAX': '117344556', 'AIRR': '138316998', 'MCAF': '127719806', 'MMER': '123527355', 'RPHI': '132753910', 'DPOL': '127881747', 'MAEA': '128202886', 'OBI': '106876031', 'OSN': '115212732', 'LJP': '135474687', 'LAK': '106152373 106165653', 'SMM': 'Smp_071840', 'SHX': 'MS3_00010760', 'OVI': 'T265_07435', 'EGL': 'EGR_01502', 'LLON': '135496715 135496727 135497369', 'NVE': '5499252 5506713', 'EPA': '110241409', 'ATEN': '116298045', 'ADF': '107346466', 'AMIL': '114976577', 'MCAZ': '138052159', 'MFOO': '137997271', 'PDAM': '113672178', 'SPIS': '111329391', 'DGT': '114518112', 'XEN': '124443737', 'HMG': '100211738', 'HSY': '130641601', 'RES': '135688116', 'TAD': 'TRIADDRAFT_64046', 'AQU': '100641546', 'ATH': 'AT1G64190 AT3G02360 AT5G41670', 'ALY': '9304654 9318292 9323978', 'CRB': '17877984 17891102 17894748', 'CSAT': '104704051 104714780 104719828 104724532 104730319 104744311 104753089 104756002 104756927 104763795', 'EUS': 'EUTSA_v10020604mg EUTSA_v10023427mg EUTSA_v10023511mg', 'BRP': '103838225 103843012 103864104 103870918', 'BNA': '106349212 106352176 106382867 106389066 106389242 106446309 106452617 125587578', 'BOE': '106293463 106317971 106340355 106342558', 'RSZ': '108827544 108855044 108861451', 'THJ': '104809348 104817722 104820969 104827148', 'CPAP': '110809446 110813014', 'CIT': '102610712 102611501 102626400', 'CIC': 'CICLE_v10011597mg CICLE_v10019859mg CICLE_v10023851mg

In [39]:
dict_data.keys()

dict_keys(['ENTRY', 'SYMBOL', 'NAME', 'PATHWAY', 'MODULE', 'REACTION', 'BRITE', 'DBLINKS', 'GENES', 'REFERENCE'])

In [43]:
dict_data['REACTION']

['R01528',
 '6-phospho-D-gluconate:NADP+',
 '2-oxidoreductase',
 '(decarboxylating)',
 'R10221',
 '6-phospho-D-gluconate:NAD+',
 '2-oxidoreductase',
 '(decarboxylating)']

In [44]:
import re

# 示例数据
reaction_list = [
    'R01528', '6-phospho-D-gluconate:NADP+', '2-oxidoreductase', '(decarboxylating)',
    'R10221', '6-phospho-D-gluconate:NAD+', '2-oxidoreductase', '(decarboxylating)'
]

# 提取所有符合 RXXXXX 格式的编号
reaction_numbers = [
    item for item in reaction_list 
    if re.fullmatch(r'R\d{5}', item)  # 严格匹配 R+5位数字
]

print(reaction_numbers)  # 输出: ['R01528', 'R10221']

['R01528', 'R10221']

In [62]:
import os
from datetime import datetime

# 创建日志目录（如果不存在）
log_dir = '../data/NRRL_1/7_Annotation/logs'
os.makedirs(log_dir, exist_ok=True)

# 定义日志文件路径
log_file = os.path.join(log_dir, 'kegg_api_processing.log')
def write_log(message, log_path=log_file):
    """将带时间戳的日志写入文件和打印到控制台"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] {message}"
    
    # 写入日志文件
    with open(log_path, 'a', encoding='utf-8') as f:
        f.write(log_entry + '\n')
    
    # 同时打印到控制台
    # print(log_entry)

In [ ]:
from bioservices import KEGG
import pandas as pd
import re
from tqdm import tqdm

starttime = datetime.now()

# 初始化KEGG服务
k = KEGG()

# 读取数据
chr_kegg_metabolism = pd.read_csv('../data/NRRL_1/7_Annotation/chr.kegg.metabolism.csv')

# 预先创建新列
chr_kegg_metabolism["R number"] = None

for index, row in tqdm(chr_kegg_metabolism.iterrows(), total=len(chr_kegg_metabolism),  desc="Processing KEGG Entries"):
    ko_number = row['KO number']
    try:
        # 调用API
        data = k.get(ko_number)
        
        if not data: # 处理空响应
            raise ValueError(f"Empty response for {ko_number}")
            
        dict_data = k.parse(data)
        
        # 提取反应编号（带异常处理）
        reaction_numbers = []
        if "REACTION" in dict_data:
            reactions = dict_data["REACTION"]
            if isinstance(reactions, str):
                reactions = [reactions]
            # 严格匹配 RXXXXX 格式
            reaction_numbers = [
                item.strip() for item in reactions
                if re.fullmatch(r'R\d{5}', item.strip()) # 去除空格后匹配
            ]
        
        # 将列表保存到新列（用分号分隔）
        chr_kegg_metabolism.at[index, "R number"] = "; ".join(reaction_numbers)
        
        # 写入日志
        write_log(f"Processed {ko_number}: Found {len(reaction_numbers)} reactions")
    
    except Exception as e:
        error_msg = f"Error processing {ko_number}: {str(e)}"
        write_log(error_msg)
        chr_kegg_metabolism.at[index, "R number"] = "Error"
        continue

chr_kegg_metabolism.to_csv(
    '../data/NRRL_1/7_Annotation/chr.kegg_metabolism_with_reactions.csv', 
    index=False
)
write_log("Processing completed. Results saved.")

endtime = datetime.now()
print({endtime - starttime})

In [52]:
# 读取时指定列类型，并将 NaN 替换为空字符串
chr_kegg_metabolism_with_reactions = pd.read_csv(
    '../data/NRRL_1/7_Annotation/chr.kegg_metabolism_with_reactions.csv',
    dtype={'R number': str}  # 强制转为字符串
).fillna({'R number': ''})  # 将 NaN 替换为空字符串

In [53]:
# 统计 R number 总数
r_count = 0
for _, row in chr_kegg_metabolism_with_reactions.iterrows():
    r_number = row['R number']
    if r_number:  # 跳过空字符串
        r_list = r_number.split(';')
        r_count += len(r_list)

print(f"Total R numbers: {r_count}")

Total R numbers: 1910

In [8]:
# chr.kegg.reactions.csv
from bioservices import KEGG
import pandas as pd
from datetime import datetime
import os
from tqdm import tqdm
import time

starttime = datetime.now()

# 定义日志文件路径
log_dir = '../data/NRRL_1/7_Annotation/logs'
log_file = os.path.join(log_dir, 'kegg_api_processing2.log')
def write_log(message, log_path=log_file):
    """将带时间戳的日志写入文件和打印到控制台"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] {message}"
    
    # 写入日志文件
    with open(log_path, 'a', encoding='utf-8') as f:
        f.write(log_entry + '\n')
    
    # 同时打印到控制台
    # print(log_entry)
    
# pd.DataFrame: Reaction ID	Reaction (Long)	Reaction (Short)	Reversible	Enzyme
# 创建存储结果的DataFrame
reaction_df = pd.DataFrame(columns=[
    "Reaction ID", 
    "Reaction (Long)", 
    "Reaction (Short)", 
    "Reversible",
    "Enzyme"
])

# 初始化KEGG服务
k = KEGG()

# 读取带反应编号的数据
chr_kegg_metabolism_with_reactions = pd.read_csv(
    '../data/NRRL_1/7_Annotation/chr.kegg_metabolism_with_reactions.csv',
    dtype={'R number': str}
).fillna({'R number': ''})

processed_reactions = set()  # 记录已处理过的反应，避免重复获取

for _, row in tqdm(chr_kegg_metabolism_with_reactions.iterrows(), total=len(chr_kegg_metabolism_with_reactions), desc="Processing KEGG reactions"):
    r_number = row['R number'].strip()
    if not r_number:  # 跳过空字符串
        continue
    r_list = [r_id.strip() for r_id in r_number.split(';')]
    for r_id in r_list:
         # 跳过已处理或空值
        if not r_id or r_id in processed_reactions:
            continue
        try: 
            # API速率控制 (每秒最多3次)
            # time.sleep(0.34)
            # 获取反应数据
            data = k.get(r_id)
            if not data:
                raise ValueError(f"Empty response for {r_id}")
            dict_data = k.parse(data)
            # 解析数据 
            reaction_long = dict_data.get('DEFINITION', '')
            reaction_short = dict_data.get('EQUATION', '')
            # 根据方程中的箭头类型判断可逆性
            reversible = '<=>' in reaction_short  
            # 提取酶编号
            enzymes = dict_data.get('ENZYME', [])            
            # 添加到结果DataFrame
            new_row = pd.DataFrame([{
                "Reaction ID": r_id,
                "Reaction (Long)": reaction_long,
                "Reaction (Short)": reaction_short,
                "Reversible": reversible,
                "Enzyme": ";".join(enzymes)
            }])
            reaction_df = pd.concat([reaction_df, new_row], ignore_index=True)
            processed_reactions.add(r_id)
            # 写入日志
            write_log(f"Processed {r_id} successfully")
        except Exception as e:
            error_msg = f"Error processing {r_id}: {str(e)}"
            write_log(error_msg)
            # 记录错误条目
            error_row = pd.DataFrame([{
                "Reaction ID": r_id,
                "Reaction (Long)": "ERROR",
                "Reaction (Short)": "ERROR",
                "Reversible": "ERROR",
                "Enzyme": "ERROR"
            }])
            reaction_df = pd.concat([reaction_df, error_row], ignore_index=True)
            continue
# 保存最终结果
reaction_df.to_csv('../data/NRRL_1/7_Annotation/chr.kegg.reactions.csv', index=False)

endtime = datetime.now()
print(endtime - starttime)

Processing KEGG reactions: 100%|██████████| 848/848 [21:32<00:00,  1.52s/it]

0:21:34.427135

In [2]:
from bioservices import KEGG
k = KEGG()
data = k.get('R01206')
dict_data = k.parse(data)
print(dict_data.keys())

dict_keys(['ENTRY', 'NAME', 'DEFINITION', 'EQUATION', 'REMARK', 'RCLASS', 'ENZYME', 'PATHWAY', 'BRITE', 'ORTHOLOGY'])

In [3]:
for key, value in dict_data.items():
    print(key, ':',value)

ENTRY : R01206                      Reaction
NAME : ['[1,4-(N-acetyl-beta-D-glucosaminyl)]n glycanohydrolase']
DEFINITION : Chitin + H2O <=> N-Acetyl-D-glucosamine + Chitin
EQUATION : C00461 + C00001 <=> C00140 + C00461
REMARK : ['Same as: R06081']
RCLASS : RC00467  C00140_C00461
ENZYME : ['3.2.1.14']
PATHWAY : {'rn00520': 'Amino sugar and nucleotide sugar metabolism', 'rn01100': 'Metabolic pathways'}
BRITE : Enzymatic reactions [BR:br08201]
             3. Hydrolase reactions
              3.2  Glycosylases
               3.2.1  Glycosidases, i.e. enzymes that hydrolyse O- and S-glycosyl compounds
                3.2.1.14
                 R01206  Chitin + H2O <=> N-Acetyl-D-glucosamine + Chitin
ORTHOLOGY : {'K01183': 'chitinase [EC:3.2.1.14]', 'K13381': 'bifunctional chitinase/lysozyme [EC:3.2.1.14 3.2.1.17]', 'K20547': 'basic endochitinase B [EC:3.2.1.14]'}

class A = Metabolism，缺失Spinosad
如何判断反应是否可逆

In [9]:
import pandas as pd

# 示例数据
df = pd.DataFrame({
    'col1': [1, 2, 3, 3, None, 4],
    'col2': [3, 4, 5, 5, None, 6]
})

# 提取两列并处理缺失值与重复值
set_col1 = set(df['col1'].dropna().unique())
set_col2 = set(df['col2'].dropna().unique())

# 计算交集
common_elements = set_col1.intersection(set_col2)
count = len(common_elements)
common_list = sorted(common_elements)  # 排序后的列表

# 输出结果
print("共同元素的数量:", count)
print("共同元素列表:", common_list)

共同元素的数量: 2
共同元素列表: [np.float64(3.0), np.float64(4.0)]

In [10]:
reactions_tju = pd.read_csv('../data/reactions+kcat.csv')
reactions_sjtu = pd.read_csv('../data/NRRL_1/7_Annotation/chr.kegg.reactions.csv')
set_reactions_tju = set(reactions_tju['Reaction ID'])
set_reactions_sjtu = set(reactions_sjtu['Reaction ID'])
common_reactions = set_reactions_tju.intersection(set_reactions_sjtu)
print(f"共同反应数量: {len(common_reactions)}")

共同反应数量: 839

--------------------------------------------------------------------------------------------------------------------------------------

In [24]:
from bioservices import KEGG
import pandas as pd
import os
from datetime import datetime
from tqdm import tqdm

starttime = datetime.now()

# 定义日志文件路径
log_dir = '../data/NRRL_1/7_Annotation/logs'
log_file = os.path.join(log_dir, 'kegg_api_processing3.log')
def write_log(message, log_path=log_file):
    """将带时间戳的日志写入文件和打印到控制台"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] {message}"
    
    # 写入日志文件
    with open(log_path, 'a', encoding='utf-8') as f:
        f.write(log_entry + '\n')
    
    # 同时打印到控制台
    # print(log_entry)
    
# pd.DataFrame: Metabolite ID	Name Formula/Composition
# 创建存储结果的DataFrame
metabolite_df = pd.DataFrame(columns=[
    "Metabolite ID", 
    "Name",
    "Formula/Composition",
    "Compartment"
])

processed_metabolites = set()  # 记录已处理过的代谢物，避免重复获取

reactions_df = pd.read_csv('../data/NRRL_1/7_Annotation/chr.kegg.reactions.csv')

k = KEGG()

for _, row in tqdm(reactions_df.iterrows(), total=len(reactions_df), desc="Processing KEGG Metabolites"):
    reaction_short = row['Reaction (Short)']
    reactants_products = []
    # 查询各个反应物的分子式
    reactants = reaction_short.split(' <=> ')[0].split(' + ')
    products = reaction_short.split(' <=> ')[1].split(' + ')
    for reactant in reactants:
        reactant = reactant.split(' ')[-1]  # 提取代谢物ID
        reactants_products.append(reactant)
    for product in products:
        product = product.split(' ')[-1]
        reactants_products.append(product)
    for metabolite_id in reactants_products:
        metabolite_id = metabolite_id.strip()
        if not metabolite_id or metabolite_id in processed_metabolites:
            continue
        try:
            # 获取代谢物数据
            data = k.get(metabolite_id)
            if not data:
                raise ValueError(f"Empty response for {metabolite_id}")
            dict_data = k.parse(data)
            name = formula = ''
            # 解析数据 
            if metabolite_id.startswith('C'):
                name = dict_data.get('NAME', '')[0]
                formula = dict_data.get('FORMULA', '')
            if metabolite_id.startswith('G'):
                name = dict_data.get('ENTRY', '').split()[1]
                formula = dict_data.get('COMPOSITION', '')
            # 添加到结果DataFrame
            new_row = pd.DataFrame([{
                "Metabolite ID": metabolite_id,
                "Name": name,
                "Formula/Composition": formula
                "Compartment": 'Cytosol'
            }])
            metabolite_df = pd.concat([metabolite_df, new_row], ignore_index=True)
            processed_metabolites.add(metabolite_id)
            # 写入日志
            write_log(f"Processed {metabolite_id} successfully")
        except Exception as e:
            error_msg = f"Error processing {metabolite_id}: {str(e)}"
            write_log(error_msg)
            # 记录错误条目
            error_row = pd.DataFrame([{
                "Metabolite ID": metabolite_id,
                "Name": "ERROR",
                "Formula/Composition": "ERROR"
            }])
            metabolite_df = pd.concat([metabolite_df, error_row], ignore_index=True)
            continue

metabolite_df.to_csv('../data/NRRL_1/7_Annotation/chr.kegg.metabolites.csv', index=False)
endtime = datetime.now()
print(endtime - starttime)

Processing KEGG Metabolites: 100%|██████████| 1529/1529 [14:54<00:00,  1.71it/s]

0:14:55.117075

R06177 G10555 + G10557(n) <=> di-trans,poly-cis-Undecaprenyl diphosphate + G10557(n+1) 
R04241 C00002 + C03541(n) + C00025 <=> C00008 + C00009 + C03541(n+1)

In [11]:
reaction_short = '1.897 C00043 + 3.794 C00052 <=> 5.691 C00015 + C00420'
reactants_products = reaction_short.split(' <=> ')
reactants = reactants_products[0].split(' + ')
products = reactants_products[1].split(' + ')
print(reactants)
print(products)

['1.897 C00043', '3.794 C00052']
['5.691 C00015', 'C00420']

In [17]:
data = k.get('C02987')
dict_data = k.parse(data)
print(dict_data.keys())

dict_keys(['ENTRY', 'NAME', 'FORMULA', 'REACTION', 'PATHWAY', 'MODULE', 'ENZYME', 'DBLINKS', 'ATOM', 'BOND', 'BRACKET'])

In [18]:
dict_data['NAME']

['L-Glutamyl-tRNA(Glu)']

In [14]:
dict_data['FORMULA']

'C20H28N6O13PR(C5H8O6PR)n'

In [19]:
data = k.get('G10555')
dict_data = k.parse(data)
print(dict_data.keys())

dict_keys(['ENTRY', 'COMPOSITION', 'REMARK', 'REACTION', 'ENZYME', 'BRITE', 'DBLINKS', 'NODE', 'EDGE'])

In [20]:
dict_data['ENTRY']

'G10555                      Glycan'

In [21]:
dict_data['ENTRY'].split()[1]

'Glycan'

In [16]:
dict_data['COMPOSITION']

'(GlcNAc)1 (MurNAc)1 (D-Ala-D-Ala-A2pm-gamma-D-Glu-Ala)1 (PP-Und)1'

---------------------------------------------------------------------------------------------------------------------------------------

In [28]:
import pandas as pd
from collections import defaultdict

# 原始数据示例
data = {
    'orf_name': ['chr_3', 'chr_27', 'chr_30', 'chr_64', 'chr_66', 'chr_96', 'chr_100', 'chr_101'],
    'KO number': ['K00033', 'K01658', 'K05364', 'K00012', 'K00681', 'K01126', 'K22336', 'K01478'],
    'R number': ['R01528; R10221', 'R00985; R00986', 'R04519; R06177', 'R00286',
                 'R00494; R01262; R01687; R03867; R03916; R03970; R03971; R04935',
                 'R01030; R01470', 'R00078', 'R00552']
}
# 读取时指定列类型，并将 NaN 替换为空字符串
chr_kegg_metabolism_with_reactions = pd.read_csv(
    '../data/NRRL_1/7_Annotation/chr.kegg_metabolism_with_reactions.csv',
    dtype={'R number': str}  # 强制转为字符串
).fillna({'R number': ''})  # 将 NaN 替换为空字符串
# 创建R编号到orf_name的映射字典（一个R编号可能对应多个orf）
r_to_orf = defaultdict(set)

for _, row in chr_kegg_metabolism_with_reactions.iterrows():
    r_numbers = [r.strip() for r in row['R number'].split(';')]
    for r in r_numbers:
        r_to_orf[r].add(row['orf_name'])

# 转换为普通字典，并将集合转为排序列表
r_to_orf = {k: sorted(list(v)) for k, v in r_to_orf.items()}

In [29]:
r_to_orf

{'R01528': ['chr_3'],
 'R10221': ['chr_3'],
 'R00985': ['chr_27', 'chr_6576'],
 'R00986': ['chr_27', 'chr_6576'],
 'R04519': ['chr_30'],
 'R06177': ['chr_30'],
 'R00286': ['chr_64'],
 'R00494': ['chr_66'],
 'R01262': ['chr_66'],
 'R01687': ['chr_66'],
 'R03867': ['chr_66'],
 'R03916': ['chr_66'],
 'R03970': ['chr_66'],
 'R03971': ['chr_66'],
 'R04935': ['chr_66'],
 'R01030': ['chr_96'],
 'R01470': ['chr_96'],
 'R00078': ['chr_100'],
 'R00552': ['chr_101'],
 'R11325': ['chr_111', 'chr_112'],
 'R00691': ['chr_120', 'chr_1771'],
 'R01373': ['chr_120', 'chr_1771'],
 '': ['chr_1081',
  'chr_1254',
  'chr_135',
  'chr_1362',
  'chr_160',
  'chr_1821',
  'chr_1827',
  'chr_1828',
  'chr_1829',
  'chr_1830',
  'chr_1855',
  'chr_2616',
  'chr_3284',
  'chr_3289',
  'chr_3290',
  'chr_3292',
  'chr_3397',
  'chr_348',
  'chr_397',
  'chr_398',
  'chr_4237',
  'chr_4454',
  'chr_4456',
  'chr_4469',
  'chr_4842',
  'chr_546',
  'chr_548',
  'chr_6147',
  'chr_6173',
  'chr_6621',
  'chr_6660',
  'chr_6905',
  'chr_7031',
  'chr_7032',
  'chr_7033',
  'chr_7034',
  'chr_7035',
  'chr_7037',
  'chr_7038',
  'chr_7400',
  'chr_851',
  'chr_909'],
 'R00505': ['chr_136'],
 'R09009': ['chr_136'],
 'R12080': ['chr_137'],
 'R04620': ['chr_141'],
 'R12078': ['chr_161'],
 'R12079': ['chr_161'],
 'R00694': ['chr_193', 'chr_7657'],
 'R00734': ['chr_193', 'chr_7657'],
 'R03243': ['chr_193'],
 'R03893': ['chr_194'],
 'R05510': ['chr_194'],
 'R05511': ['chr_194'],
 'R06835': ['chr_194'],
 'R06838': ['chr_194'],
 'R08120': ['chr_194'],
 'R08121': ['chr_194'],
 'R09136': ['chr_194'],
 'R09220': ['chr_194'],
 'R09222': ['chr_194'],
 'R01357': ['chr_195'],
 'R01728': ['chr_229', 'chr_3042'],
 'R01213': ['chr_271'],
 'R00480': ['chr_292'],
 'R02291': ['chr_293'],
 'R01678': ['chr_312'],
 'R03355': ['chr_312'],
 'R04633': ['chr_312'],
 'R05112': ['chr_312'],
 'R05994': ['chr_312'],
 'R06010': ['chr_312'],
 'R07807': ['chr_312'],
 'R00235': ['chr_342'],
 'R00236': ['chr_342'],
 'R00316': ['chr_342'],
 'R00925': ['chr_342', 'chr_4631'],
 'R00926': ['chr_342', 'chr_4631'],
 'R01354': ['chr_342', 'chr_4631'],
 'R08555': ['chr_345'],
 'R00022': ['chr_350', 'chr_4633'],
 'R10831': ['chr_350'],
 'R01132': ['chr_401'],
 'R01229': ['chr_401'],
 'R02142': ['chr_401'],
 'R08237': ['chr_401'],
 'R08238': ['chr_401'],
 'R08245': ['chr_401'],
 'R00424': ['chr_403'],
 'R00428': ['chr_403'],
 'R04639': ['chr_403'],
 'R05046': ['chr_403'],
 'R05048': ['chr_403'],
 'R03066': ['chr_3616', 'chr_404'],
 'R03067': ['chr_3616', 'chr_404'],
 'R03504': ['chr_405'],
 'R11037': ['chr_405'],
 'R11073': ['chr_405'],
 'R03503': ['chr_3616', 'chr_406'],
 'R02473': ['chr_412'],
 'R00489': ['chr_2253', 'chr_413', 'chr_5343'],
 'R02971': ['chr_414', 'chr_6374'],
 'R03018': ['chr_414', 'chr_6374'],
 'R04391': ['chr_414', 'chr_6374'],
 'R05633': ['chr_437'],
 'R05637': ['chr_438'],
 'R06977': ['chr_453', 'chr_5706'],
 'R01206': ['chr_1124', 'chr_458'],
 'R02334': ['chr_1124', 'chr_458'],
 'R02737': ['chr_472'],
 'R11783': ['chr_472'],
 'R02778': ['chr_473'],
 'R01920': ['chr_478'],
 'R08359': ['chr_478'],
 'R10147': ['chr_491'],
 'R00768': ['chr_495'],
 'R03223': ['chr_502'],
 'R10712': ['chr_502'],
 'R07463': ['chr_503'],
 'R10247': ['chr_505'],
 'R03471': ['chr_507'],
 'R04509': ['chr_507'],
 'R03472': ['chr_508'],
 'R01800': ['chr_513'],
 'R02055': ['chr_514'],
 'R09735': ['chr_516'],
 'R04031': ['chr_535'],
 'R01764': ['chr_541'],
 'R02672': ['chr_541'],
 'R00214': ['chr_557'],
 'R11372': ['chr_558'],
 'R09394': ['chr_563'],
 'R02017': ['chr_1343', 'chr_572'],
 'R02018': ['chr_1343', 'chr_572'],
 'R02019': ['chr_1343', 'chr_572'],
 'R02024': ['chr_1343', 'chr_572'],
 'R01334': ['chr_573'],
 'R04173': ['chr_608'],
 'R05085': ['chr_608'],
 'R00351': ['chr_610'],
 'R00131': ['chr_2934', 'chr_2935', 'chr_2936', 'chr_611'],
 'R13420': ['chr_2934', 'chr_2935', 'chr_2936', 'chr_611'],
 'R00277': ['chr_612'],
 'R00278': ['chr_612'],
 'R01710': ['chr_612'],
 'R01711': ['chr_612'],
 'R01602': ['chr_615'],
 'R10619': ['chr_615'],
 'R00760': ['chr_618'],
 'R00867': ['chr_618'],
 'R03920': ['chr_618'],
 'R00848': ['chr_622'],
 'R04311': ['chr_624'],
 'R01351': ['chr_633'],
 'R10850': ['chr_642'],
 'R12902': ['chr_642'],
 'R08166': ['chr_643'],
 'R10127': ['chr_663'],
 'R09083': ['chr_749'],
 'R00955': ['chr_760'],
 'R02301': ['chr_769'],
 'R00289': ['chr_770'],
 'R04072': ['chr_782'],
 'R07620': ['chr_782'],
 'R11399': ['chr_782'],
 'R01716': ['chr_3043', 'chr_784'],
 'R03659': ['chr_786'],
 'R04773': ['chr_786'],
 'R05634': ['chr_794'],
 'R09289': ['chr_801'],
 'R01049': ['chr_802'],
 'R00416': ['chr_803'],
 'R05332': ['chr_803'],
 'R02222': ['chr_806'],
 'R12173': ['chr_806'],
 'R00087': ['chr_813'],
 'R00103': ['chr_1140', 'chr_813'],
 'R00287': ['chr_813'],
 'R00426': ['chr_813'],
 'R00515': ['chr_813'],
 'R00662': ['chr_813'],
 'R03004': ['chr_1140', 'chr_813'],
 'R03036': ['chr_813'],
 'R11323': ['chr_813'],
 'R00658': ['chr_817'],
 'R03409': ['chr_823'],
 'R00578': ['chr_902'],
 'R00238': ['chr_1964', 'chr_941'],
 'R01177': ['chr_1964', 'chr_941'],
 'R00891': ['chr_943'],
 'R01290': ['chr_943'],
 'R04942': ['chr_943'],
 'R00999': ['chr_945'],
 'R01288': ['chr_945'],
 'R02026': ['chr_945'],
 'R02508': ['chr_945'],
 'R03217': ['chr_945'],
 'R03260': ['chr_945'],
 'R04944': ['chr_945'],
 'R04945': ['chr_945'],
 'R04946': ['chr_945'],
 'R00220': ['chr_4064', 'chr_947'],
 'R00996': ['chr_947'],
 'R01372': ['chr_948'],
 'R02521': ['chr_948'],
 'R01639': ['chr_955'],
 'R08528': ['chr_961'],
 'R01082': ['chr_1917', 'chr_970'],
 'R00762': ['chr_973'],
 'R04780': ['chr_973'],
 'R05884': ['chr_979'],
 'R08210': ['chr_979'],
 'R09846': ['chr_989'],
 'R00366': ['chr_1023'],
 'R02457': ['chr_1023'],
 'R02894': ['chr_1023'],
 'R02923': ['chr_1023'],
 'R04221': ['chr_1023'],
 'R07400': ['chr_1023'],
 'R04734': ['chr_1024'],
 'R04365': ['chr_1041'],
 'R02734': ['chr_1047'],
 'R09837': ['chr_1058'],
 'R09839': ['chr_1058'],
 'R00899': ['chr_1061', 'chr_1448'],
 'R04951': ['chr_1061', 'chr_1448'],
 'R00798': ['chr_1077', 'chr_1079', 'chr_1080', 'chr_4171'],
 'R01106': ['chr_1077', 'chr_1079', 'chr_1080', 'chr_4171'],
 'R09497': ['chr_1077', 'chr_1079', 'chr_1080'],
 'R11104': ['chr_1140'],
 'R02094': ['chr_1168'],
 'R02098': ['chr_1168'],
 'R05066': ['chr_1182'],
 'R08219': ['chr_1185'],
 'R02767': ['chr_1195'],
 'R04533': ['chr_1195', 'chr_5497'],
 'R04534': ['chr_1195', 'chr_5497'],
 'R04536': ['chr_1195', 'chr_5497'],
 'R04543': ['chr_1195', 'chr_5497'],
 'R04566': ['chr_1195', 'chr_5497'],
 'R04953': ['chr_1195', 'chr_5497'],
 'R04964': ['chr_1195', 'chr_5497'],
 'R07763': ['chr_1195'],
 'R10116': ['chr_1195'],
 'R10120': ['chr_1195'],
 'R11671': ['chr_1195', 'chr_1674', 'chr_4185'],
 'R00533': ['chr_1215'],
 'R00009': ['chr_1225'],
 'R00602': ['chr_1225', 'chr_2777'],
 'R02670': ['chr_1225', 'chr_2777'],
 'R02356': ['chr_1238', 'chr_3858'],
 'R03408': ['chr_1238', 'chr_3858'],
 'R08286': ['chr_1238', 'chr_3858'],
 'R08287': ['chr_1238', 'chr_3858'],
 'R08390': ['chr_1238', 'chr_3858', 'chr_4975'],
 'R08391': ['chr_1238', 'chr_3858', 'chr_4975'],
 'R08392': ['chr_1238', 'chr_3858', 'chr_4975'],
 'R09404': ['chr_1238', 'chr_3858'],
 'R09408': ['chr_1238', 'chr_3858', 'chr_4975'],
 'R02164': ['chr_1247', 'chr_1248', 'chr_7395', 'chr_7396'],
 'R00582': ['chr_1255'],
 'R01268': ['chr_1265'],
 'R01724': ['chr_1266'],
 'R01519': ['chr_1278'],
 'R02933': ['chr_1278'],
 'R03751': ['chr_1278', 'chr_2964'],
 'R00260': ['chr_1280'],
 'R00720': ['chr_1283'],
 'R02720': ['chr_1283'],
 'R03531': ['chr_1283'],
 'R08243': ['chr_1283'],
 'R03145': ['chr_1290'],
 'R01055': ['chr_1300'],
 'R08836': ['chr_1302'],
 'R01424': ['chr_1310'],
 'R11582': ['chr_1322'],
 'R01676': ['chr_1324'],
 'R01768': ['chr_1327',
  'chr_2618',
  'chr_2620',
  'chr_4693',
  'chr_4694',
  'chr_4695'],
 'R02103': ['chr_1327',
  'chr_2618',
  'chr_2620',
  'chr_4693',
  'chr_4694',
  'chr_4695'],
 'R00670': ['chr_1329'],
 'R00178': ['chr_1330'],
 'R01051': ['chr_1333'],
 'R02750': ['chr_1333'],
 'R01209': ['chr_1341'],
 'R04441': ['chr_1341'],
 'R05070': ['chr_1341'],
 'R02133': ['chr_1355'],
 'R09993': ['chr_1355'],
 'R07411': ['chr_1369'],
 'R00237': ['chr_1407'],
 'R02407': ['chr_1408'],
 'R03154': ['chr_1408'],
 'R02540': ['chr_1411'],
 'R03096': ['chr_1411'],
 'R03180': ['chr_1411'],
 'R03909': ['chr_1411'],
 'R05551': ['chr_1411'],
 'R05590': ['chr_1411'],
 'R00243': ['chr_1428'],
 'R01056': ['chr_1458'],
 'R09030': ['chr_1458'],
 'R00942': ['chr_1485'],
 'R02237': ['chr_1485'],
 'R04241': ['chr_1485'],
 'R00124': ['chr_1493'],
 'R00139': ['chr_1493'],
 'R00156': ['chr_1493'],
 'R00330': ['chr_1493'],
 'R00331': ['chr_1493'],
 'R00570': ['chr_1493'],
 'R00722': ['chr_1493'],
 'R01137': ['chr_1493'],
 'R01857': ['chr_1493'],
 'R02093': ['chr_1493'],
 'R02326': ['chr_1493'],
 'R02331': ['chr_1493'],
 'R03530': ['chr_1493'],
 'R11894': ['chr_1493'],
 'R11895': ['chr_1493'],
 'R12853': ['chr_1493'],
 'R01026': ['chr_1500'],
 'R00239': ['chr_1508'],
 'R03313': ['chr_1516'],
 'R00137': ['chr_1519'],
 'R03005': ['chr_1519'],
 'R01466': ['chr_1525'],
 'R05086': ['chr_1525'],
 'R00994': ['chr_1534'],
 'R04426': ['chr_1534'],
 'R10052': ['chr_1534'],
 'R00409': ['chr_1536', 'chr_3426'],
 'R00479': ['chr_1536'],
 'R00025': ['chr_1539'],
 'R00705': ['chr_1549'],
 'R00706': ['chr_1549'],
 'R00922': ['chr_1549'],
 'R00935': ['chr_1549'],
 'R03158': ['chr_1551'],
 'R05064': ['chr_1551'],
 'R00509': ['chr_1562'],
 'R00529': ['chr_1562', 'chr_1563'],
 'R04928': ['chr_1562'],
 'R04929': ['chr_1562', 'chr_1563'],
 'R02021': ['chr_1564'],
 'R00859': ['chr_1566'],
 'R03600': ['chr_1566'],
 'R06447': ['chr_1584'],
 'R01856': ['chr_1593'],
 'R01494': ['chr_1621'],
 'R06518': ['chr_1621'],
 'R06528': ['chr_1621'],
 'R00742': ['chr_1670',
  'chr_2533',
  'chr_2622',
  'chr_3355',
  'chr_3356',
  'chr_4639'],
 'R01859': ['chr_1670', 'chr_2533'],
 'R04386': ['chr_1670', 'chr_2622', 'chr_4639'],
 'R02768': ['chr_1671'],
 'R04355': ['chr_1671', 'chr_5497'],
 'R04726': ['chr_1671', 'chr_5497'],
 'R04952': ['chr_1671', 'chr_5497'],
 'R04957': ['chr_1671', 'chr_5497'],
 'R04960': ['chr_1671', 'chr_5497'],
 'R04963': ['chr_1671', 'chr_5497'],
 'R04968': ['chr_1671', 'chr_5497'],
 'R07762': ['chr_1671'],
 'R10115': ['chr_1671'],
 'R10119': ['chr_1671'],
 'R12049': ['chr_1672'],
 'R10707': ['chr_1673'],
 'R01626': ['chr_1674', 'chr_5497'],
 'R00014': ['chr_1681', 'chr_3335', 'chr_6514', 'chr_6515', 'chr_6923'],
 'R00209': ['chr_1681', 'chr_1795', 'chr_1796', 'chr_6514', 'chr_6515'],
 'R01699': ['chr_1681', 'chr_6514', 'chr_6515'],
 'R03270': ['chr_1681', 'chr_6514', 'chr_6515'],
 'R01658': ['chr_1697', 'chr_3168', 'chr_3187', 'chr_5078'],
 'R02003': ['chr_1697', 'chr_3168', 'chr_3187', 'chr_5078'],
 'R02061': ['chr_1697', 'chr_3187', 'chr_5078'],
 'R01826': ['chr_1702', 'chr_3053'],
 'R00251': ['chr_1731', 'chr_1732', 'chr_2844'],
 'R06529': ['chr_1748'],
 'R07302': ['chr_1748'],
 'R04594': ['chr_1755'],
 'R01226': ['chr_1770'],
 'R00189': ['chr_1778'],
 'R00253': ['chr_1780'],
 'R07767': ['chr_1789'],
 'R12423': ['chr_1789'],
 'R12424': ['chr_1789'],
 'R07766': ['chr_1793'],
 'R07769': ['chr_1793'],
 'R12427': ['chr_1793'],
 'R12428': ['chr_1793'],
 'R02569': ['chr_1795'],
 'R01210': ['chr_1796', 'chr_3667', 'chr_3668', 'chr_4941'],
 'R01221': ['chr_1796', 'chr_4624', 'chr_4628', 'chr_6538'],
 'R01651': ['chr_1796', 'chr_3667', 'chr_3668', 'chr_4941'],
 'R01698': ['chr_1796'],
 'R01933': ['chr_1796'],
 'R03171': ['chr_1796', 'chr_3667', 'chr_3668', 'chr_4941'],
 'R03815': ['chr_1796'],
 'R07618': ['chr_1796'],
 'R08549': ['chr_1796'],
 'R01090': ['chr_1803'],
 'R01214': ['chr_1803'],
 'R02199': ['chr_1803'],
 'R08622': ['chr_1803'],
 'R08626': ['chr_1803'],
 'R10991': ['chr_1803'],
 'R05223': ['chr_1804'],
 'R11174': ['chr_1804'],
 'R04148': ['chr_1805'],
 'R05221': ['chr_1806'],
 'R05222': ['chr_1806'],
 'R06558': ['chr_1806'],
 'R00185': ['chr_1812'],
 'R02108': ['chr_1813'],
 'R02112': ['chr_1813'],
 'R11262': ['chr_1813'],
 'R00650': ['chr_1816'],
 'R11063': ['chr_1816'],
 'R01073': ['chr_1824'],
 'R00390': ['chr_1836', 'chr_3746'],
 'R01280': ['chr_1836', 'chr_3746'],
 'R02241': ['chr_1844'],
 'R09381': ['chr_1844'],
 'R00756': ['chr_1846'],
 'R03236': ['chr_1846'],
 'R03237': ['chr_1846'],
 'R03238': ['chr_1846'],
 'R03239': ['chr_1846'],
 'R04779': ['chr_1846'],
 'R07653': ['chr_1858'],
 'R09690': ['chr_1858'],
 'R09719': ['chr_1858'],
 'R09744': ['chr_1858'],
 'R09745': ['chr_1858'],
 'R09746': ['chr_1858'],
 'R07168': ['chr_1860'],
 'R00470': ['chr_1877'],
 'R05605': ['chr_1877'],
 'R02036': ['chr_1878'],
 'R01122': ['chr_1889'],
 'R02735': ['chr_1890'],
 'R00291': ['chr_1907'],
 'R02984': ['chr_1907'],
 'R01092': ['chr_1908'],
 'R01931': ['chr_1910'],
 'R03105': ['chr_1910'],
 'R02187': ['chr_1938'],
 'R02189': ['chr_1938'],
 'R01185': ['chr_1939'],
 'R01186': ['chr_1939'],
 'R01187': ['chr_1939'],
 'R02100': ['chr_1943'],
 'R11896': ['chr_1943'],
 'R05636': ['chr_1958'],
 'R01975': ['chr_1963', 'chr_2158'],
 'R03026': ['chr_1963', 'chr_2158', 'chr_2262', 'chr_6957'],
 'R04170': ['chr_1963', 'chr_2158', 'chr_6957'],
 'R04737': ['chr_1963', 'chr_2158'],
 'R04738': ['chr_1963', 'chr_2158', 'chr_6957'],
 'R04739': ['chr_1963', 'chr_2158'],
 'R04740': ['chr_1963', 'chr_2158', 'chr_6957'],
 'R04741': ['chr_1963', 'chr_2158'],
 'R04743': ['chr_1963'],
 'R04744': ['chr_1963', 'chr_2158', 'chr_6957'],
 'R04745': ['chr_1963', 'chr_2158'],
 'R04746': ['chr_1963', 'chr_2158', 'chr_6957'],
 'R04748': ['chr_1963', 'chr_2158'],
 'R04749': ['chr_1963', 'chr_2158', 'chr_6957'],
 'R07889': ['chr_1963'],
 'R07890': ['chr_1963'],
 'R07893': ['chr_1963'],
 'R07894': ['chr_1963'],
 'R07897': ['chr_1963'],
 'R07898': ['chr_1963'],
 'R00927': ['chr_1964'],
 'R03778': ['chr_1964'],
 'R03858': ['chr_1964'],
 'R03991': ['chr_1964'],
 'R04546': ['chr_1964'],
 'R04742': ['chr_1964'],
 'R04747': ['chr_1964'],
 'R07891': ['chr_1964'],
 'R07895': ['chr_1964'],
 'R07899': ['chr_1964'],
 'R07937': ['chr_1964'],
 'R07953': ['chr_1964'],
 'R03197': ['chr_1970'],
 'R04972': ['chr_1970'],
 'R03222': ['chr_1971'],
 'R04178': ['chr_1971'],
 'R11522': ['chr_1972'],
 'R02472': ['chr_1987'],
 'R00667': ['chr_2000'],
 'R02035': ['chr_2001', 'chr_6190'],
 'R01976': ['chr_2017'],
 'R05576': ['chr_2017'],
 'R06941': ['chr_2017', 'chr_2158'],
 'R05284': ['chr_2021'],
 'R05367': ['chr_2021'],
 'R05368': ['chr_2021'],
 'R05369': ['chr_2021'],
 'R05370': ['chr_2021'],
 'R07669': ['chr_2021'],
 'R07670': ['chr_2021'],
 'R02487': ['chr_2026'],
 'R02488': ['chr_2026'],
 'R10074': ['chr_2026'],
 'R09954': ['chr_2034'],
 'R00761': ['chr_2036'],
 'R01621': ['chr_2036'],
 'R00315': ['chr_2037'],
 'R01353': ['chr_2037'],
 'R01305': ['chr_2050'],
 'R03187': ['chr_2052', 'chr_2053'],
 'R00875': ['chr_2079'],
 'R01896': ['chr_2079'],
 'R06294': ['chr_2090'],
 'R06295': ['chr_2090'],
 'R06296': ['chr_2090'],
 'R06297': ['chr_2090'],
 'R10067': ['chr_2090'],
 'R00431': ['chr_2122'],
 'R00726': ['chr_2122'],
 'R05623': ['chr_2147'],
 'R03045': ['chr_2158', 'chr_6957'],
 'R03276': ['chr_2158'],
 'R04137': ['chr_2158', 'chr_6957'],
 'R04203': ['chr_2158', 'chr_5817'],
 'R04204': ['chr_2158', 'chr_6957'],
 'R04224': ['chr_2158', 'chr_6957'],
 'R05305': ['chr_2158'],
 'R06411': ['chr_2158', 'chr_6957'],
 'R06412': ['chr_2158', 'chr_6957'],
 'R06942': ['chr_2158', 'chr_6957'],
 'R08093': ['chr_2158', 'chr_6957'],
 'R08094': ['chr_2158'],
 'R00908': ['chr_2160', 'chr_6801'],
 'R01648': ['chr_2160', 'chr_6801'],
 'R00264': ['chr_2164', 'chr_5438'],
 'R00631': ['chr_2164'],
 'R00710': ['chr_2164'],
 'R00904': ['chr_2164'],
 'R01752': ['chr_2164'],
 'R01986': ['chr_2164'],
 'R02549': ['chr_2164', 'chr_4196'],
 'R02678': ['chr_2164'],
 'R02940': ['chr_2164'],
 'R02957': ['chr_2164'],
 'R03283': ['chr_2164'],
 'R03869': ['chr_2164'],
 'R04065': ['chr_2164'],
 'R04506': ['chr_2164'],
 'R04903': ['chr_2164'],
 'R05050': ['chr_2164'],
 'R05237': ['chr_2164'],
 'R05238': ['chr_2164'],
 'R05286': ['chr_2164'],
 'R06366': ['chr_2164'],
 'R08146': ['chr_2164'],
 'R07262': ['chr_2180'],
 'R00130': ['chr_2192'],
 'R06946': ['chr_2198'],
 'R06947': ['chr_2198'],
 'R10070': ['chr_2198'],
 'R01175': ['chr_2222', 'chr_8198'],
 'R01279': ['chr_2222', 'chr_7105', 'chr_8198'],
 'R02661': ['chr_2222', 'chr_7799'],
 'R03172': ['chr_2222', 'chr_7799'],
 'R03777': ['chr_2222', 'chr_7105', 'chr_8198'],
 'R03857': ['chr_2222', 'chr_7105', 'chr_8198'],
 'R03990': ['chr_2222', 'chr_7105', 'chr_8198'],
 'R04095': ['chr_2222'],
 'R04751': ['chr_2222', 'chr_7105', 'chr_8198'],
 'R04754': ['chr_2222', 'chr_7105', 'chr_8198'],
 'R00947': ['chr_2224'],
 'R01025': ['chr_2235'],
 'R02565': ['chr_2237'],
 'R02566': ['chr_2237'],
 'R02382': ['chr_2250', 'chr_3317'],
 'R02529': ['chr_2250', 'chr_3317'],
 'R02613': ['chr_2250', 'chr_3317'],
 'R03139': ['chr_2250'],
 'R04027': ['chr_2250'],
 'R04300': ['chr_2250', 'chr_3317'],
 'R06154': ['chr_2250'],
 'R06740': ['chr_2250'],
 'R00261': ['chr_2253'],
 'R01682': ['chr_2253'],
 'R02466': ['chr_2253'],
 'R01179': ['chr_2259', 'chr_3352'],
 'R01359': ['chr_2259', 'chr_3352'],
 'R07832': ['chr_2259', 'chr_3352'],
 'R04428': ['chr_2263', 'chr_5497'],
 'R04535': ['chr_2263', 'chr_5497'],
 'R04537': ['chr_2263', 'chr_5497'],
 'R04544': ['chr_2263', 'chr_5497'],
 'R04568': ['chr_2263', 'chr_5497'],
 'R04954': ['chr_2263', 'chr_5497'],
 'R04965': ['chr_2263', 'chr_5497'],
 'R10208': ['chr_2263'],
 'R00623': ['chr_2265', 'chr_3260'],
 'R00754': ['chr_2265', 'chr_3119', 'chr_3260'],
 'R02124': ['chr_2265', 'chr_3260'],
 'R04805': ['chr_2265'],
 'R04880': ['chr_2265', 'chr_3260'],
 'R05233': ['chr_2265', 'chr_3260'],
 'R05234': ['chr_2265', 'chr_3260'],
 'R06917': ['chr_2265', 'chr_3260'],
 'R06927': ['chr_2265', 'chr_3260'],
 'R07105': ['chr_2265', 'chr_3260'],
 'R08281': ['chr_2265', 'chr_3260'],
 'R08306': ['chr_2265', 'chr_3260'],
 'R08310': ['chr_2265', 'chr_3260'],
 'R05287': ['chr_2266', 'chr_4094'],
 'R11357': ['chr_2330'],
 'R09955': ['chr_2331'],
 'R06363': ['chr_2348'],
 'R01374': ['chr_2383'],
 'R09493': ['chr_2383'],
 'R03443': ['chr_2393'],
 'R00259': ['chr_2395', 'chr_6680'],
 'R02282': ['chr_2395'],
 'R02649': ['chr_2396'],
 'R02283': ['chr_2397'],
 'R04475': ['chr_2397', 'chr_7780'],
 'R01398': ['chr_2398'],
 'R01086': ['chr_2401'],
 'R00841': ['chr_2406'],
 'R00104': ['chr_2409'],
 'R00571': ['chr_2413'],
 'R00573': ['chr_2413'],
 'R00512': ['chr_2423'],
 'R01665': ['chr_2423'],
 'R01513': ['chr_2437'],
 'R01012': ['chr_2439', 'chr_6999', 'chr_7000'],
 'R02262': ['chr_2441'],
 'R12696': ['chr_2441'],
 'R01123': ['chr_2448'],
 'R00669': ['chr_2449', 'chr_7469'],
 'R10553': ['chr_2449'],
 'R11428': ['chr_2453', 'chr_2455'],
 'R00374': ['chr_2454'],
 'R05704': ['chr_2454'],
 'R02280': ['chr_2456'],
 'R04374': ['chr_2457'],
 'R10467': ['chr_2486'],
 'R07210': ['chr_2512', 'chr_2528'],
 'R10206': ['chr_2512', 'chr_2528'],
 'R00465': ['chr_2514', 'chr_4200'],
 'R01392': ['chr_2514', 'chr_4200'],
 'R09281': ['chr_2514'],
 'R05706': ['chr_2528'],
 'R04385': ['chr_2533', 'chr_2622', 'chr_3356'],
 'R13256': ['chr_2533'],
 'R01067': ['chr_2554'],
 'R01641': ['chr_2554'],
 'R01830': ['chr_2554'],
 'R06590': ['chr_2554'],
 'R08714': ['chr_2556'],
 'R06398': ['chr_2567'],
 'R09385': ['chr_2567'],
 'R09389': ['chr_2567'],
 'R09393': ['chr_2567'],
 'R05062': ['chr_2595'],
 'R05198': ['chr_2595'],
 'R05285': ['chr_2595'],
 'R01366': ['chr_2612'],
 'R00010': ['chr_2646', 'chr_3979'],
 'R05645': ['chr_2655'],
 'R09768': ['chr_2655'],
 'R09769': ['chr_2655'],
 'R08034': ['chr_2664', 'chr_2665'],
 'R07644': ['chr_2746', 'chr_4635', 'chr_4636', 'chr_5016'],
 'R03707': ['chr_2750', 'chr_3307'],
 'R09078': ['chr_2750', 'chr_3307'],
 'R10505': ['chr_2750', 'chr_3307'],
 'R00191': ['chr_2770'],
 'R00698': ['chr_2777'],
 'R02596': ['chr_2777'],
 'R03919': ['chr_2777'],
 'R04007': ['chr_2777'],
 'R07443': ['chr_2777'],
 'R11906': ['chr_2777'],
 'R03182': ['chr_2818'],
 'R12933': ['chr_2818'],
 'R12934': ['chr_2818'],

In [43]:
# orf_names = ['chr_4560', 'chr_4561']  
# orf_names = ['chr_4562']
orf_names = ''

In [44]:
gene_list = []
gene_str = ''
if not orf_names:
    gene_list.append(orf_names)
elif len(orf_names) == 1:
    gene_str = orf_names[0]
    gene_list.append(gene_str)
else:
    # 将列表转换为逗号分隔的字符串
    gene_str = " and ".join(orf_names)
    gene_str = '( ' + gene_str + ' )'
    # 将结果存入列表
    gene_list.append(gene_str)
print(gene_str, gene_list)

chr_4562 ['']

In [47]:
import os
from datetime import datetime

# 定义日志文件路径
log_dir = '../data/NRRL_1/7_Annotation/logs'
log_file = os.path.join(log_dir, 'kegg_api_processing4.log')
def write_log(message, log_path=log_file):
    """将带时间戳的日志写入文件和打印到控制台"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] {message}"
    
    # 写入日志文件
    with open(log_path, 'a', encoding='utf-8') as f:
        f.write(log_entry + '\n')
    
    # 同时打印到控制台
    # print(log_entry)

reactions_df = pd.read_csv('../data/NRRL_1/7_Annotation/chr.kegg.reactions.csv')
# reaction.gene_reaction_rule = '( STM2378 or STM1197 )'

# 创建空列表存储结果（比直接操作DataFrame更高效）
gene_list = []

# 遍历每一行反应式
for index, row in reactions_df.iterrows():
    r_id = row['Reaction ID']  # 获取当前行的R编号
    gene_str = ''
    
    # 从字典中获取对应的orf_name列表（若无则返回''）
    orf_names = r_to_orf.get(r_id, '')
    
    if not orf_names:
        gene_list.append(orf_names)
    elif len(orf_names) == 1:
        gene_str = orf_names[0]
        gene_list.append(gene_str)
    else:
        # 将列表转换为逗号分隔的字符串
        gene_str = " and ".join(orf_names)
        gene_str = '( ' + gene_str + ' )'
        # 将结果存入列表
        gene_list.append(gene_str)
    
    write_log(f"Processed {r_id} => {gene_str}")

# 最后将列表添加到DataFrame
reactions_df['Genes'] = gene_list
reactions_df.to_csv('../data/NRRL_1/7_Annotation/chr.kegg.reactions_with_genes.csv')

In [48]:
reactions_df

,Reaction ID,Reaction (Long),Reaction (Short),Reversible,Enzyme,Genes
0,R01528,6-Phospho-D-gluconate + NADP+ <=> D-Ribulose 5...,C00345 + C00006 <=> C00199 + C00011 + C00005 +...,True,1.1.1.44;1.1.1.351,chr_3
1,R10221,6-Phospho-D-gluconate + NAD+ <=> D-Ribulose 5-...,C00345 + C00003 <=> C00199 + C00011 + C00004 +...,True,1.1.1.343;1.1.1.351,chr_3
2,R00985,Chorismate + Ammonia <=> Anthranilate + Pyruva...,C00251 + C00014 <=> C00108 + C00022 + C00001,True,4.1.3.27,( chr_27 and chr_6576 )
3,R00986,Chorismate + L-Glutamine <=> Anthranilate + Py...,C00251 + C00064 <=> C00108 + C00022 + C00025,True,4.1.3.27,( chr_27 and chr_6576 )
4,R04519,Undecaprenyl-diphospho-N-acetylmuramoyl-(N-ace...,C05898 + C11827 <=> C04574 + C11827,True,2.4.99.28,chr_30
...,...,...,...,...,...,...
1524,R07896,OPC4-CoA + FAD <=> trans-2-Enoyl-OPC4-CoA + FADH2,C16335 + C00016 <=> C16336 + C01352,True,1.3.3.6,chr_8198
1525,R07934,"(6Z,9Z,12Z,15Z,18Z,21Z)-Tetracosahexaenoyl-CoA...",C16168 + C00007 <=> C16374 + C00027,True,1.3.3.6,chr_8198
1526,R07950,"(6Z,9Z,12Z,15Z,18Z)-Tetracosapentaenoyl-CoA + ...",C16172 + C00007 <=> C16387 + C00027,True,1.3.3.6,chr_8198
1527,R12356,Propanoyl-CoA + Oxygen <=> Propenoyl-CoA + Hyd...,C00100 + C00007 <=> C00894 + C00027,True,1.3.3.6,chr_8198
1528,R01939,L-2-Aminoadipate + 2-Oxoglutarate <=> 2-Oxoadi...,C00956 + C00026 <=> C00322 + C00025,True,2.6.1.39,chr_8218